# Script to build TED with Nestor80
# https://github.com/Konamiman/Nestor80/

N80 ENTRY.MAC
N80 SUBTED.MAC
N80 GETPUT.MAC
N80 TEDSTR.MAC
N80 MAIN.MAC
LK80 -c 0100h -o TED.COM ENTRY.REL SUBTED.REL GETPUT.REL TEDSTR.REL MAIN.REL
