                ;TED subroutines

if1
                .printx * Assemble: SUBTED.MAC *
endif

                include OFFSET.MAC      ;Ge‹ndiceerde variabelen offsets

bs              equ 08h
tab             equ 09h
lf              equ 0Ah
home            equ 0Bh
clsHm           equ 0Ch
cr              equ 0Dh
esc             equ 1Bh
right           equ 1Ch
left            equ 1Dh
up              equ 1Eh
down            equ 1Fh
del             equ 127
nul             equ 0FFh
ctrlZ           equ 1Ah

enaSlt          equ 24H

txtCgp          equ 0F3B7H
csrY            equ 0F3DCH
csrX            equ 0F3DDH
rg1sav          equ 0f3e0h
pbID            equ 0f976h
newKey          equ 0FBE5H
intFlg          equ 0FC9BH
h.lptO          equ 0FFB6h

memMan          equ 4D00H
use2            equ 2
alloc           equ 10
deAlloc         equ 20
iniChk          equ 30
getCur          equ 32
info            equ 50
getTsrID        equ 62

delFile         equ 13H
create          equ 22
rename          equ 23
setDma          equ 26
rbRead          equ 39
open            equ 15
getTime         equ 2CH
rbWrite         equ 38
close           equ 16
openFH          equ 43H
createFH        equ 44H
readFH          equ 48H
writeFH         equ 49H
seek            equ 4AH
del2            equ 4DH
ren2            equ 4EH
parse           equ 5BH

                global bouwOp,haalPrt,prtRg,prtRg2,insReg,regNum
                global scrlUp,getName,mul16,div16,decToBin
                global dcSet,deci2,prtSav,prtStr,strOut,dcBuf
                global setVdp,ldrMv2,ldrVm2,nLdrMv,nStWrt
                global NCHPTI,NCHPUT,NCHGET,CONTROL,MEMVOL,REGLANG
                global DSKERR,KARERR,GRAPH,P2SEG
                global RECERR,ONDERBR,ERROR,fullPageTab
                global CHECKAG,INT,LOADIN2,indentBlok
                global BCDSET,PRTBCD,MAKEKAR,TOACCESS,GETFLEN
                global TOCHECK,CODE,ldrMv2,ldrVm2,strLen
                global COPYBLOK,MOVEBLOK,WISBLOK,RESETBLOK,STARTBLOK
                global ENDBLOK
                global SAVDEF,SAVINS
                global NAAM2,MAKETXT,SFCB2,SAVEBLOK,SAVE
                global LOADBLOK,LOAD,LOAD2,LDBLK2,NOTFOUND
                global UPDATE,UPDAT2,MAAKFCB,SAVE1,SV0B,ZOEKMAP,PUTP2
                global FINDPB,ZOEK,AGAIN
                global EXTBIOS,MEMMAN,MMUSE2,FRESEG,DEALLOC
                global getPageStop,chkPageTab,disVdpInt,enaVdpInt

                ;Externals in MAIN.MAC - Subroutines, variabelen etc.

                ext CALSUM,CHKTED,KANTLIJN,TGETNAME,DECODE,CRLTAB
                ext PRTNUM,CSRNUM,STRBUF,STRBF2,STRBF3,GETPLT,COLORS,TOCHK
                ext BIGFIL,DOS,IVLINE,KOLOMS,HM0,HLPCNT,MMTABEL
                ext BSTARTLN,BENDLN,DCOMPR,TXTCOL,NWRVRM,NRDVRM
                ext DISKBUF,DELLNO,INSLNO,CHECK2,BLKPS3,BLKCNT,BLKON,BLKOFF
                ext LASTLINE,INVOER,GETTXT,TNAME,BUF,path1Buf,TKEUZE
                ext CHSNS,CHGET,CHPUT,ESCCNT,SAVNAM,MMANERR
                ext TOREGEND,TOETS1,TOETS6,TOREGSTART,OMLAAG
                ext REMOVLN,COMLN,NOCTRL,CL0,TOMIDDEN,GETCMD,ESCAPE
                ext MESKEY,GOTOLINE,FKEYNUM,INSERT,CHKSTOP
                ext STACK,INTCNT,TMOMENT,INICLR,MSXKAR,menuXY
                ext GETCODE,ACCESS,CHECK,ADDCODE,TODOS,AUTOCNT
                ext TEDMAX,VRMEND,POINTERS,TTAB,STARTVAR,ENDVAR,TOINHOUD
                ext SEGEND,BF3PNT,EVTOPSLAAN,ZOEKBUF,VERVBUF,SAVZOEK
                ext FCB,MAIN,MAIN1,TABEL,INKCRL,CLOSEBF,STMOTR
                ext MAXPTR,FREMEM,SAVFD,SAVFE,FCB1,AANCSR,TVERSIE,RECHTS
                ext TEXTENS,SAVESTART,SAVEEND,GETOLD,KLEIN,MIDLINE,TEKEN,LINKS
                ext MESSAGE,BUFPOINT,KEYCNT,CFORMAT,GOLINE2,DELETE
                ext ENDTPA,LOADREG,VRAAGSAVE,OPSLAAN,BSPACE,BEEP,ZEKER
                ext LOADNAM,GROOTTE,BLOK,RETINS,SETBOUW,RESTSCR,THELP,DELSPC
                ext toCurLine,cmpBlank,pageTab,delPageStop,pbTsrID
                ext menuEsc,getONr

                ;Externals in TEDSTR - Taal afhankelijke scherm boodschappen

                ext indKar
                byte ext xAantPos

                ext TRECERR,TREGLEN,TONDERB,TMEMVOL,TTOMANY,TDISKVOL,TPROT
                ext TNODISK,TDSKERR,TVERERR,TKARERR,TNOTFND,TPROB,TVERVANG
                ext TSAVNAM,TLOADNAM,TSAVINS,TZOEK,TZOEK2,TWEL,TACHTER,TONV

                ext tIndent

                ext tPageTabFull,krtStart,krtEnd,tNoKrt,krtPos
                ext INSKAR
                ext VRMREG,VRMKOL,VRMPAG

                byte ext XZOEK

                ;Externals in GETPUT.MAC

                ext clear,clrNoPageTab,get,get2,put,swap,fre
                ext rnPageTab,invoegNoRn,rnPointers
                ext delStr,addLine,rTabHL,wTabHL,readHL,writeHL
                ext voegIn,zr0a,zr0b,makeTab,mmOut,getBot2
                ext delLines,zoekNum

                ;Begin van TED.COM, komt op adres 0103 Hex.

                db 'E',CLSHM,'Krakers verzieken de M.S. Aktie!',CTRLZ
                dw CRLTAB               ;Pointer naar controltoetsen, TED-INST

                db 0                    ;Lengte byte voor decimalenbuffer
DCBUF:          ds 6                    ;Decimalenbuffer
KARBUF:         ds 8                    ;8 bytes karakterpatroon
CURBREG:        dw 0
MOVSRT:         dw 0
MOVLEN:         dw 0
STRPOS:         dw 0
INDEX:          db 0
DATADR:         dw 0                    ;Volgende adres in datasegment
PNTADR:         dw 0                    ;Volgende adres in pointersegment
RENUMLN:        dw 0
strLen:         dw 0                    ;Stringlengte bij verwijderen
aantDelPnt:     dw 0                    ;Aantal te verwijderen regels
firstPntAddr:   dw 0                    ;Adres te verwijderen pointers
firstDataAddr:  dw 0                    ;Adres van te verwijderen string
nextDataAddr:   dw 0                    ;Einde te verwijderen strings
DFBUF:          db 0                    ;Datafile karakterbuffer
P2SEG:          db -1                   ;Huidig segment in Page 2

                ;DOS-2/MemMan extended bios jump table

allSeg:         jp 0                    ;Allocate segment
freSeg:         jp 0                    ;Free segment
getP1:          jp 0                    ;Get page 1 segment
putP2:          jp 0                    ;Put page 2 segment
getP2:          jp 0                    ;Get page 2 segment

mmUse2:         jp 0                    ;MemMan fastUse2 functie
extBios:        call 0ffcah             ;Call naar EXTBIO hook
                ld iy,tabel             ;Herstel IY, zekerheid troef
                ret


                ;Bouw het scherm op

bouwOp:         bit bouw,(iy-flags4)    ;Moet scherm wel opgebouwd worden?
                ret z                   ; Nee, => Terug
                res bouw,(iy-flags4)
bo1:            bit hlp,(iy+savFl2)     ;Hulpmenu op scherm?
                jr z,bo2b
                bit rstH,(iy-flags4)    ;Restore menu?
                jr z,bo2b
                res rsth,(iy-flags4)    ; Ja, toon het menu
                ld a,3+hlpCnt
                bit comLin,(iy+tabSav)
                jr z,bo2
                ld a,5+hlpCnt
bo2:            ld (iy+minLin),a
                sub hlpCnt
                ld l,a                  ;L=Bovenste Y-Pos
                call hm0                ;Bouw helpmenu op
                call prtRg              ;Print (nieuwe) huidige regel
bo2b:           ld a,(iy+minLin)        ;Begin bij bovenste regel
                ld (iy+bouwNum),a
bo3:            ld a,(iy+bouwNum)
                dec a
                cp (iy+maxLin)
                jp nc,kantLijn          ;Zet tabstops op scherm
                inc a
                inc (iy+bouwNum)
                cp (iy+yPos)
                jr z,bo3                ;Niet de huidige regel
                ld (iy+prtReg),a        ;Geef regelnummer door aan printroutine
                call haalPrt            ;Haal en print
                jr bo3                  ;Volgende regel

                ;Haal en print een regel

haalPrt:        ld d,0
                ld e,(iy+yPos)
                ld hl,(csrNum)
                or a
                sbc hl,de               ;HL=Nummer bovenste regel
                ld a,(iy+prtReg)        ;Te printen regel
                push af
                ld e,a
                add hl,de
                ex de,hl                ;DE=Stringnummer
                ld hl,strBf2            ;String naar klad buffer
                push hl
                ld (prtNum),de          ;Bewaar te printen regelnummer
                call get
                pop hl
                pop af
                jp prtRg2               ;Druk string af

                ;Print de huidige regel en locate cursor

prtRg:          ld hl,(csrNum)
                ld (prtNum),hl          ;Geef nummer te printen regel
                ld a,(iy+yPos)          ;Huidige schermpositie
                ld hl,strBuf            ;Huidige regelbuffer
                call prtRg2             ;Zet string op scherm
                ld hl,(csrNum)          ;Regelnummer
                call regNum
                ld hl,vrmKol            ;Haal VRAM adres van kolomnummer
                call nStWrt
                ld a,(iy+xPos)          ;Kolom
                add a,(iy+offset)
                call prtBcd

                ld hl,vrmPag
                call nStWrt             ;Zet VRAM adres op `pagina: '

                ld hl,0                 ;Huidig aantal pagina's is 0

                bit nPageNum,(iy+savFl3);Pagina nummer indicatie tonen?
                jr nz,pg3               ; Nee, => Toon altijd pagina 0

                ld ix,pageTab           ;Pagina tabel in IX
                ld b,h                  ;Huidig entry in pageTab = 0

calcCurPageLp:  push bc                 ;Bewaar entryteller B
                push hl                 ;Bewaar paginateller HL

                ld hl,(csrNum)          ;Huidige regel in HL
                inc hl                  ;1-based maken

                ld a,(iy+numPageStops)
                cp b                    ;Laatste entry in de tabel?
                jr z,inThisPage         ; Ja, => Regel ligt in deze pagina

                ld e,(ix+0)             ; Nee, haal volgende pagina stop
                ld d,(ix+1)
                call dCompr             ;Ligt de paginastop voorbij de regel
                jr c,inThisPage         ; Ja, => Regel ligt in deze pagina
                jr z,inThisPage

                ld l,(ix-2)             ;Haal bovenliggende paginastop
                ld h,(ix-1)

                ex de,hl                ;Grootste getal in HL
                sbc hl,de               ;Bereken aantal regels in deze pagina

                call getNumPages        ;Bereken het aantal pagina's

                pop de                  ;Haal huidig aantal pagina's
                add hl,de               ;Tel dit aantal erbij
                pop bc                  ;Herstel entry teller

                inc b                   ;Naar volgende pagina stop
                inc ix
                inc ix

                jr calcCurPageLp        ;Bereken aantal pagina's

inThisPage:     ld e,(ix-2)             ;Haal bovenliggende paginastop in DE
                ld d,(ix-1)
                or a
                sbc hl,de               ;Bereken aantal regels in deze pagina

                call getNumPages        ;Bereken het aantal pagina's

                pop de                  ;Haal huidig aantal pagina's
                add hl,de               ;Tel dit aantal erbij
                pop bc                  ;Verwijder entry teller

pg3:            call deci2              ;Paginanummer in Deci-Buf
                ld b,4                  ;Print max. 4 cijfers
                call prDeci             ;Druk getal af
                bit hlp,(iy+savFl2)     ;Hulpmenu op scherm?
                jr z,PgX
                bit rstH,(iy-flags4)    ;Restore menu?
                jr nz,pgx               ; Ja, => geen menu, geen grote letters
                bit bigLet,(iy+savFl2)  ;Grote letters?
                jr z,pgx
                ld a,(iy+xPos)          ; Ja, zet grote letters in hulpmenu
                add a,(iy+offSet)
                ld b,a
                ld a,(strBuf)
                inc a
                sub b                   ;A=LEN-XPOS
                cp 6
                jr c,pg3b
                ld a,6                  ;Maximaal 6 tekens rechts van de cursor
pg3b:           add a,b
                sub 13                  ;Cursor voor positie 13?
                ld c,1                  ; Ja, toon tekst vanaf pos. 1
                jr c,pg4
                inc a                   ; Nee, toon tekst vanaf csr. pos. -12
                ld c,a
pg4:            ld hl,strBuf
                ld d,0
                ld e,c
                add hl,de
                ld b,13                 ;13 tekens afdrukken
pg5:            ld a,(strBuf)           ;[C]=Positie van teken in Strbuf(1-255)
                cp c                    ;Einde van regel bereikt?
                ld a,' '
                jr c,pg6                ; Ja, druk alleen nog spaties af
                ld a,(hl)               ; Nee, => druk het teken (HL) groot af
pg6:            ld d,a                  ;Bewaar het teken
                ld a,(iy+xPos)
                ADD A,(IY+OFFSET)
                CP C                    ;Wordt de cursor positie afgedrukt?
                LD A,D                  ; Ja, dan vlag Z
                PUSH HL
                PUSH BC
                CALL PRTBIG             ;Druk teken af
                POP BC
                POP HL
                INC HL
                INC C
                DJNZ PG5                ;Volgende teken
PGX:            BIT COMLIN,(IY+TABSAV)  ;Editor scherm?
                RET Z
                LD HL,26*80             ;Nee, print wijzertje
                LD BC,80
                LD A,' '
                CALL BIGFIL
                LD A,(IY+XPOS)
                DEC A
                LD H,0
                LD L,A
                LD DE,26*80
                ADD HL,DE
                LD A,'^'
                JP NWRVRM


; getNumPages
;
; In:  HL=Aantal regels
; Uit: HL=Aantal pagina's
;
getNumPages:    ld a,(iy+pagLen)        ;Haal paginalengte
                or a                    ;Paglen=0?
                jr z,onePage            ; Ja, => Past altijd op 1 pagina
                push hl                 ;Bewaar aantal regels

                ld de,(koloms)          ;Haal aantal kolommen in DE
                ld h,d                  ;H=D=0
                ld l,a                  ;L=A=Paginalengte in HL
                ld a,e                  ;Is het aantal kolommen 1?
                dec a                   ; Zo ja, dan heeft mul16 geen zin
                call nz,mul16           ; Nee, kols*paglen=totale paginalengte

                ex de,hl                ;Paginalengte naar DE
                pop hl                  ;Haal aantal regels
                call div16              ;HL=regLen/pagLen
                ld a,d
                or e                    ;Rest regels?
                ret z
                inc hl                  ; Ja, die kosten ook een pagina
                ret
onePage:        ld hl,1                 ;Aantalpagina's = 1
                ret


                ;Druk teken in [A] vergroot af

PRTBIG:         PUSH BC                 ;B=13-Positie
                PUSH AF                 ;Vlag Z = Cursor positie
                LD H,0
                LD L,A                  ;Bereken positie van teken in kar.tabel
                ADD HL,HL               ; door met 8 te vermenigvuldigen
                ADD HL,HL
                ADD HL,HL
                LD DE,(TXTCGP)          ;Tel beginadres van tabel erbij
                ADD HL,DE
                LD DE,KARBUF
                LD C,8
                XOR A
                CALL NLDRMV             ;Haal patroon uit scherm vram
                POP AF                  ;Haal Z vlag
                JR NZ,PB0B              ; NZ => Geen cursor
                LD HL,KARBUF
                LD B,8
                BIT INSFL,(IY+FLAGS1)   ;Insert aan?
                JR Z,PB0                ; Nee, => Toon blok cursor
                BIT BLKC,(IY+SAVFL)     ;Blok cursor?
                JR NZ,PB0
                LD HL,KARBUF+5          ; Nee, lijncursor = insert aan
                LD B,3
PB0:            LD A,(HL)
                CPL                     ;Maak teken inverse
                LD (HL),A
                INC HL
                DJNZ PB0
PB0B:           POP AF                  ;Haal het tekennummer in A (13..1)
                NEG                     ;Bereken x positie van teken
                ADD A,13                ;13 karakters van 6 posities
                ADD A,A                 ;*2
                LD B,A
                ADD A,A                 ;*4
                ADD A,B                 ;*6
                INC A
                LD (CSRX),A
                LD A,(IY+MINLIN)
                SUB HLPCNT              ;Bereken y positie van hulpmenu
                LD HL,CSRY
                LD (HL),A
                LD B,8                  ;8 lijnen per karakter
                LD C,(IY+VDPWRITE)
                LD DE,KARBUF
PB1:            PUSH BC
                PUSH DE
                CALL SETVDP             ;Zet vdp schrijf klaar
                POP DE
                LD B,6                  ;6 kolommen per karakter
                LD A,(DE)
PB2:            RLA                     ;Schuif bit in carry
                PUSH AF
                LD A,' '
                JR NC,PB3               ;Bit is 0 => Druk spatie af
                LD A,0DBH               ;Bit is 1 => Druk Û af
PB3:            OUT (C),A
                POP AF
                DJNZ PB2                ;Volgende bit
                POP BC
                INC (HL)                ;1 regel omlaag
                INC DE                  ;Volgende lijn
                DJNZ PB1
                RET

                ;HL=String
                ;A =Schermregel, 1-based

PRTRG2:         bit dispOff,(iy-flags5) ;Scherm opbouw niet actief?
                ret nz                  ; Ja, => Geen regels tonen

                RES LONG,(IY-FLAGS2)    ;Vlag: Regel niet te lang (> 79 tekens)
                PUSH AF                 ;Bewaar Y-POS
                LD DE,SETINV            ;Ga verder met SET INVerse
                PUSH DE
                PUSH HL
                DEC A                   ;Regelnummer in [A]
                ADD A,A                 ;*2
                ADD A,A                 ;*4
                ADD A,A                 ;*8 (werkt tot max. 31 schermregels)
                LD H,0
                LD L,A                  ;Regelnummer*8 in [HL]
                LD D,H                  ;*8 bewaren in DE
                LD E,L
                ADD HL,HL               ;*16
                ADD HL,HL               ;*32
                ADD HL,DE               ;*40
                ADD HL,HL               ;*80 karakters per regel

                call nStWrt             ;Zet VDP-Write klaar op regel-start

                ld bc,9 shl 8           ;10 bytes * 8 bits = 80 tekens, buffer
                ld hl,ivLine            ;Wis colortabel van deze regel
pr1:            ld (hl),c               ;Opvullen met nul
                inc hl
                djnz pr1                ;Na de loop is [B] altijd 0
                ld (hl),1               ;Pos 80=Inverse, statusteken

                ld c,(iy+vdpWrite)
                pop hl                  ;Haal string adres
                push hl
                ld a,(hl)
                or a                    ;Lege regel?
                jp z,prtNul             ; Ja, => Print spaties

                ld d,b                  ;D=B=0
                ld e,a                  ;DE=Regellengte
                add hl,de
                ld b,(hl)               ;Haal laatste teken in B
                sbc hl,de               ;Geen carry door ADD
                ld e,(iy+offSet)
                add hl,de               ;Tel X-offset bij begin positie op
                sub e                   ;Trek X-offset van regellengte af
                jr nc,pr27              ;Nog een teken over
                xor a                   ;Alle tekens vallen links naast scherm

pr27:           inc hl                  ;Lengtebyte overslaan
                cp 80
                jr c,pr3                ;Regel past op scherm => PR3
                jr nz,pr28
                ld a,b                  ;80e teken is spatie?
                cp ' '
                jr z,pr29
pr28:           set long,(iy-flags2)    ;Vlag: toon '+' = regel te lang
pr29:           ld a,79
pr3:            push af
                or a
                jr z,pr5
                ld e,b                  ;Laatste teken in E
                ld b,a
                otir
pr5:            ld b,' '

                bit nPageStop,(iy+savFl2);Pagina-stop indikatie aan?
                jr nz,pr5c              ; Nee, => Druk statusteken af

                push de
                push bc

                ld hl,(prtNum)          ;Haal nummer huidige regel
                call getPageStop        ;Kijk of dit paginagrens is
                ld a,'S'                ;Statusteken voor harde paginastops
                jr nc,pr5a              ;Harde pagina grens => Toon 'S'

                bit pag,(iy+savFl2)     ;Gewone paginagrens tonen?
                jr z,pr5b               ; Nee, => Toon gewoon statusteken

                or a
                sbc hl,de               ;Bereken regelafstand tot pagina einde

                ld d,0                  ;DE=Paginalengte
                ld e,(iy+pagLen)
                inc e
                dec e
                jr z,pr5b               ;Paginalengte=0 => PR5B

                call div16              ;Deel regelnummer door paglengte
                ld a,d
                or e
                jr nz,pr5b              ; Rest=0? Nee, => PR5B

                ld de,(koloms)          ;Haal aantal kolommen
                dec e                   ;Is het aantal kolommen 1?
                ld a,'P'
                jr z,pr5a               ; Ja, => Snel afdrukken wegwezen
                inc e                   ;Herstel kolom aantal in DE

                call div16              ;Bereken huidige kolomnummer in DE
                inc e
                dec e
                ld a,'P'
                jr z,pr5a               ;DE=0 => Einde van pagina
                ld a,e
                add a,'0'               ;Statusteken = kolomnummer aan
pr5a:           pop bc                  ;Haal oude statusteken+I/O poort
                pop de                  ;Haal laatste teken van regel (E)
                ld b,a                  ;Nieuw statusteken in B
                pop af                  ;Haal regellengte van de stack
                push bc                 ;Statusteken op de stack
                ld b,'_'                ;Geef pagina einde weer met '_'
                jr pr5d

pr5b:           pop bc
                pop de

pr5c:           pop af                  ;Haal regellengte in A
                push bc
pr5d:           ld d,a
                ld a,79
                sub d
                jr z,pr7
pr6:            out (c),b
                dec a
                jp nz,pr6
pr7:            ld a,b
                cp '_'                  ;Pag./Kolom indikatie?
                pop bc
                ld a,b                  ;       Kolomcijfer in [A]
                jr z,pr8                ; Ja, => Klaar
                ld a,'+'                ;'+'=Regel langer als scherm
                bit long,(iy-flags2)
                jr nz,pr8
                bit edit,(iy+savFl2)    ;Edit mode?
                jr nz,pr7b              ; Ja, => Print altijd '<'
                ld a,e
                cp ' '                  ;Is laatste teken van regel spatie?
                jr z,pr8                ; Ja, => Volgende regel=dezelfde alinea
pr7b:           ld a,'<'                ; Nee, => Geef alinea einde aan
pr8:            out (c),a
                pop bc                  ;BC=Stringadres
                ld hl,(prtNum)
                ld de,(bStartLn)        ;Ligt regel in blok?
                call dCompr             ;Vergelijk HL met DE
                ret c
                ld a,0                  ;Startpositie op 0 indien
                jr nz,pr9               ; huidige regel niet 1e in het blok is
                ld a,(iy-bSrtPos)       ;Haal 1e teken van 1e regel
pr9:            sub (iy+offset)
                jr nc,pr10
                xor a
pr10:           ld e,a                  ;E=1e teken
                push de
                ld de,(bEndLn)
                call dCompr             ;Regel na blokeinde?
                pop de
                ld a,(bc)               ;Haal reglen
                jr z,pr10b              ;Laatste regel => PR10B
                ret nc
                jr pr11
pr10b:          ld b,(iy-bEndPos)
                cp b                    ;Vgl reglen met blokeide pos.
                jr c,pr11               ; Blokeinde groter => Reglen=Max
                ld a,b
pr11:           sub (iy+offset)
                ret c                   ; Valt links van scherm
                ret z
                cp 80                   ;Max 79 tekens
                jr c,pr12
                ld a,79
pr12:           sub e
                ret z                   ; Kleiner dan 1e teken
                ret c

                ;Inverteer blok-regel: E=1e inverse teken, A=Lengte

                PUSH AF
                XOR A                   ;Wis carry
                SRL E                   ;Deel E door 8, rest in A
                RRA
                SRL E
                RRA
                SRL E
                RRA
                LD D,0
                LD HL,IVLINE
                ADD HL,DE               ;Tel xpos/8 bij bufferadres op
                LD B,5
IT2:            SRL A                   ;Maak doorschuif van rest af
                DJNZ IT2
                LD B,10000000B          ;Bit masker in B
                OR A                    ;Klaar?
                JR Z,IT4
IT3:            SRL B
                DEC A                   ;Roteer B A keer
                JR NZ,IT3
IT4:            POP DE                  ;D=Aantal tekens
IT4B:           LD A,(HL)               ;Zet het bit in Tabel
                OR B
                LD (HL),A
                SRL B
                JR NC,IT5
                LD B,10000000B
                INC HL                  ;Volgende byte
IT5:            DEC D
                JR NZ,IT4B              ;Volgende teken
                RET

SETINV:         POP BC                  ;B=Y-Pos
                LD DE,10                ;10 bytes per regel
                LD HL,-10               ;Begin bij -10
SEI2:           ADD HL,DE               ;bereken regel begin
                DJNZ SEI2
                LD DE,(TXTCOL)
                ADD HL,DE
                EX DE,HL
                LD HL,IVLINE
                LD C,10
                JP NLDVM0               ;Copieer IVLINE naar colortabel

                ;Print een regel met lengte nul

PRTNUL:         LD HL,(PRTNUM)
                LD DE,(LASTLINE)
                XOR A                   ;Geen carry, reglen=0
                SBC HL,DE               ;Huidige regel voorbij de laatste?
                LD E,A                  ;       Laatste teken van regel <> ' '
                JP C,PR3                ; Nee, => Print '<'
                LD B,79
                LD A,' '
PN1:            OUT (C),A               ; Ja, huidige regel leeg maken
                DJNZ PN1
                LD A,':'                ;Geef EOF aan met ':'
                OUT (C),A
                POP HL                  ;Haal stringadres van stack
                RET

; getPageStop
;
; Bepaalt het regelnummer van de harde paginagrens op of vlak boven regel [HL]
; Tabel met paginagrenzen wordt binair doorzocht
;
; In:      HL=Regelnr (0-based)
; Uit:     HL=Regelnr (1-based)
;          Indien waarde gevonden:
;            Carry=clear
;            DE=Pagina-einde (1-based)
;            IX=Positie van DE in pageTab
;          anders
;            Carry=set
;            DE=Bovenliggend pagina-einde (1-based)
;            IX+0, IX+1 = Positie in pagetab om (HL) in op te slaan
;
; Wijzigt: AF, BC, DE, HL, IX
;
getPageStop:    ld b,h                  ;Gezochte waarde opslaan
                ld c,l
                inc bc                  ;Maak 1e tekstregel nr. 1

                ld hl,pageTab           ;Ondergrens=Basisadres
                ld a,(iy+numPageStops)  ;Haal totaal aantal paginastops
                or a                    ;Nul paginastops?
                scf
                jr z,quitGetPage        ; Ja, => Niet gevonden

                ex de,hl                ;DE=Ondergrens

                ld hl,quitGetPage       ;Terugkeer entry op de stack zetten
                push hl

                dec a                   ;Aantal entries 0-based maken
                ld h,0                  ;Aantal entries naar HL
                ld l,a
                sla l                   ;*2 bytes per entry
                rl h
                add hl,de               ;HL=Bovengrens

getPageLoop:    push hl                 ;Bewaar bovengrens op de stack
                add hl,de               ;Midden=(Boven+Onder)\2
                rr h                    ;\2
                rr l

                ld a,e                  ;Haal lage adresbyte van ondergrens
                rra                     ;Schuif bit 0 in de carry
                jr c,makeEven           ;Bit 0=1, => Maak bit 0 van midden 1
                set 0,l                 ;Align op word-grens (2 bytes) + 1
                jr getHighByte          ;HL wijst nu naar highbyte van entry
makeEven:       bit 0,l                 ;Align op wordgrens+1, = highbyte
                jr z,getHighByte        ; => Staat al op highbyte
                inc hl                  ;Zet HL op highbyte v/h element

getHighByte:    ld a,(hl)               ;Haal high-byte van middelste element
                dec hl                  ;Naar low-byte en vergelijk met
                cp b                    ; gezochte waarde (zowel C als Z vlag)
                jr nz,pageNotEqual      ; => Indien gezochte waarde <> element
                ld a,(hl)               ;Haal low-byte
                cp c                    ;Ook vergelijken
pageNotEqual:   jr nc,elmTooLarge       ; => Indien element >= gezochte regel
                ex de,hl                ;Ondergrens=Midden+1
                inc de                  ;Naar volgende element
                inc de
                pop hl                  ;Herstel de bovengrens
                jr pageContLp           ;Volgende iteratie

elmTooLarge:    inc sp                  ;Haal oude bovengrens weg
                inc sp
                ret z                   ;Klaar indien waardes gelijk zijn

                dec hl                  ;Bovengrens = Midden - 1
                dec hl

pageContLp:     ld a,l                  ;Vergelijk boven- en ondergrens
                cp e
                ld a,h
                sbc a,d
                jr nc,getPageLoop       ;Verder indien nog minstens 1 element
                inc hl                  ;Herstel pointer naar volgende
                inc hl                  ; paginastop
                ret                     ;Geen paginastop, => terug met carry

quitGetPage:    push hl                 ;Tabelpointer naar IX
                pop ix
                ld e,(ix-2)             ;Indien niet gevonden, neem boven
                ld d,(ix-1)             ; liggende paginastop
                ld h,b                  ;Regelnr. terug naar HL
                ld l,c
                ret c                   ;Klaar indien geen pagestop gevonden
                ld e,(ix+0)             ;Haal gevonden tabelentry in DE
                ld d,(ix+1)
                ret

; chkPageTab
;
; Verwijdert paginastops die voorbij het huidige teksteinde liggen.
; De paginastops kunnen voorbij het teksteinde terecht komen wanneer er
; een .TED file gelezen wordt met daarin een te lange paginastop-tabel.
; Nadat een .TED file geladen is - of na een error - moet deze routine dus
; worden aangeroepen.
;
chkPageTab:     ld hl,(lastLine)        ;Haal teksteinde
                call getPageStop        ;Haal paginastop

                push ix                 ;Tabelpointer naar HL
                pop hl

                jr c,putTabEndHere      ;Stop niet gevonden => (HL)=tabeleinde

                inc hl                  ;Stop gevonden, tabeleinde
                inc hl                  ; staat 1 entry verder

putTabEndHere:  ld de,pageTab           ;Begin van de tabel in DE
                or a
                sbc hl,de               ;Bereken aantal bytes
                srl h                   ;Delen door 2 bytes per entry
                rr l                    ;[L]=Entry nummer
                ld (iy+numPageStops),l  ;Tabel afkappen op einde van tekst
                ret


                ;Zoek hetzelfde als de vorige keer

again:          call evtOpslaan
                ld a,(zoekBuf)
                or a
                jp z,notFound           ;Valt niets te zoeken
                jp zoekEntry

                ;Zoeken van een woord

zoek:           call evtOpslaan
                ld hl,tZoek
                ld c,8
                call invoer
                ld l,(iy+minLin)
                inc l
                ld h,xZoek              ;Haal x-pos op van zoektekst (15)
                ld (csry),hl
                ld hl,vervBuf
                call prtStr             ;Toon oude vervangbuffer alvast
                ld hl,csry
                dec (hl)
                ld hl,savZoek
                ld de,zoekBuf
                ld bc,51                ;1 len.byte+50 tekens
                ldir                    ;Haal oude zoekstring op
                ld hl,zoekBuf
                ld e,0                  ;Alle letters toegestaan
                ld b,50                 ;String van 50 tekens
                call getOld             ;Haal op (en toon evt. oude zoekstring)
                ld a,c
                or a
                jp z,notFound           ;Niets te zoeken
                ld b,0
                inc c                   ;Lengte byte ook meenemen
                ld hl,buf
                ld de,zoekBuf
                push hl
                push bc
                ldir                    ;Zet string in zoekbuffer
                pop bc
                pop hl
                ld de,savZoek
                ldir                    ;Bewaar te zoeken string voor later
                ld hl,(csry)
                inc l                   ;1 regel naar onderen
                ld h,xZoek              ;Haal x-pos op van zoektekst (15)
                ld (csry),hl
                ld hl,vervBuf
                ld e,0
                ld b,50
                call getOld             ;Haal tekst waarin vervangen moet
                ld b,0                  ; worden
                inc c
                ld hl,buf
                ld de,vervBuf
                ldir
                ld hl,(csry)
                inc l
                inc l
                ld h,1
                push hl
pz0:            pop hl
                ld (csry),hl
                push hl
                ld de,tZoek2
                call strOut             ;Print standaardtekst
                pop hl
                push hl
                ld h,8
                ld (csry),hl
                ld de,tWel
                bit bovOndK,(iy-flags3)
                call nz,strOut          ;Print ' Wel'
                pop hl
                push hl
                inc l
                ld h,6
                ld (csry),hl
                ld de,tAchter           ;Achteruit zoeken
                bit voorAch,(iy-flags3)
                call nz,strOut
                pop hl
                push hl
                inc l
                inc l
                ld h,6
                ld (csry),hl
                ld de,tOnv              ;'On'voorwaardelijk zoeken
                bit onv,(iy-flags4)
                call nz,strOut
pz1:            call chsns
                jr z,pz1
                call nChGet             ;Wacht op toets
                cp cr
                jr z,pz3
                cp esc                  ;Escape=terug
                pop hl
                ret z
                push hl
                cp 255                  ;Fkey?
                jr nz,pz1
                call nChGet             ;Haal nummer
                ld b,10b                ;B=Bitmasker
                cp 1
                jr z,pz2
                ld b,1
                cp 2
                jr z,pz2
                cp 3
                jr nz,pz1
                ld a,(iy-flags4)
                xor 1000000b            ;Wissel On-/Voorwaardelijk vervangen
                ld (iy-flags4),a
                jp pz0
pz2:            ld a,(iy-flags3)
                xor b
                ld (iy-flags3),a
                jp pz0
pz3:            pop hl

zoekEntry:      ld hl,tMoment
                call message            ;Momentje...
                bit bovOndK,(iy-flags3) ;Verschil klein/hoofdletter?
                jr nz,pz5
                LD HL,ZOEKBUF
                LD B,(HL)
                INC HL
PZ4:            LD A,(HL)
                CALL KLEIN              ; Nee, => Alles klein
                LD (HL),A
                INC HL
                DJNZ PZ4
PZ5:            LD HL,ZOEKBUF           ;Maak een indextabel in de diskbuffer
                CALL MAAKTABEL          ; de hand van de zoekstring in Zoekbuf
                LD (IY+REGLOW),0        ;Druk elke 64 regels het regelnummer af
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)       ;Zoek vanaf cursor
                INC A                   ;1 verder als cursor
                LD E,A
                LD A,(STRBUF)
                CP E                    ;Cursor aan einde regel?
                LD A,E
                LD DE,(CSRNUM)
                JR C,ZOEK2B             ; Ja, => Zoek1
                DEC A
                CALL POS2               ;Zoek vanaf pos. [A]
                LD DE,(CSRNUM)
                JR ZOEK2                ;Zoek verder in dezelfde regel
ZOEK1:          LD DE,(CSRNUM)          ;DE=Te onderzoeken regel
                INC DE
ZOEKLOOP:       LD A,E
                AND 01000000B
                CP (IY+REGLOW)          ;Bit 6 veranderd?
                JR Z,ZKL1               ; Nee, => Niet afdrukken
                LD (IY+REGLOW),A
                EX DE,HL
                CALL REGNUM             ;Zet regelnummer op scherm
                EX DE,HL
ZKL1:           PUSH DE                 ;Regelnummer in DE

                if not autoDemo         ;Geen keyscan vanaf diskfile
                   call chkStop         ;Test op ESC/^Stop
                endif

                LD HL,STRBUF            ;Tijdelijke buffer
                CALL GET                ;Haal regel op
                CALL POS                ;Zoek positie in string
                POP DE
ZOEK2:          OR A
                JR NZ,ZOEKFOUND         ;Gevonden
ZOEK2B:         BIT VOORACH,(IY-FLAGS3) ;Vooruit/achteruit
                JR Z,ZOEK3
                LD A,D
                OR E                    ;Begin v/d tekst?
                JP Z,NOTFOUND
                DEC DE
                JP ZOEKLOOP
ZOEK3:          inc de
                ld hl,(lastLine)        ;Laatste regel?
                ld a,l                  ;Vergelijk HL met DE
                cp e
                ld a,h
                sbc a,d
                jp nc,zoekLoop
                jp notFound             ;Niet gevonden

ZOEKFOUND:      EX DE,HL                ; DE wordt huidige regel
                CALL MIDLINE            ;Ga naar gevonden regel
                LD A,(INDEX)
                DEC A
                CALL TOMIDDEN           ;Zet cursor neer
                LD A,(VERVBUF)          ;Vervangen?
                OR A
                RET Z                   ; Nee, klaar

                ;Vervang een tekst

VERVANG:        CALL BOUWOP             ;Bouw scherm op
                CALL PRTRG
                CALL CHKSTOP            ;Test op ESC/^Stop
                BIT ONV,(IY-FLAGS4)     ;Onvoorwaardelijk vervangen?
                JR NZ,VERV1B            ; Ja, => Niets vragen
                LD HL,TVERVANG
                CALL MESSAGE            ;Vervangen j/n ?
                LD A,(IY+XPOS)
                LD (CSRX),A
                LD A,(IY+YPOS)
                LD (CSRY),A
VERV1:          CALL INKCRL             ;Ook ^J of ^N
                CP 'N'
                RET Z
                CP 'J'
                JR NZ,VERV1
VERV1B:         LD A,(ZOEKBUF)          ;Haal lengte op
                LD B,A
VERV2:          PUSH BC
                CALL DELETE             ;Wis letter
                CALL PRTRG              ;Druk af
                POP BC
                DJNZ VERV2              ;Volgende letter
                LD A,(IY+FLAGS1)
                PUSH AF
                SET INSFL,(IY+FLAGS1)   ;Insert aan
                LD DE,0
VERV3:          INC DE                  ;Sla lengte-byte over
                PUSH DE
                LD HL,VERVBUF
                ADD HL,DE               ;Haal vervangletter
                LD A,(HL)
                SET NKL,(IY-FLAGS3)     ;Negeer kantlijnen
                CALL TEKEN              ;Voeg letter in
                POP DE
                LD A,(VERVBUF)          ;Is alles vervangen?
                CP E
                JR NZ,VERV3             ; Nee, => Verv3
                CALL LINKS              ;Cursor 1 naar links
                CALL PRTRG
                POP AF
                LD (IY+FLAGS1),A        ;Herstel insert vlag
                BIT ONV,(IY-FLAGS4)
                JP NZ,AGAIN             ; => Volgende vervangen
                RET                     ;Voorwaardelijk vervangen => Terug

                ;Maak zoek-tabel in DISKBUF a.d.h. van [HL] ZOEKBUF

MAAKTABEL:      LD A,(HL)
                OR A                    ;Lengte zoekstring = 0?
                RET Z                   ; Ja, => RET
                LD DE,DISKBUF
                LD B,0
MTB1:           LD (DE),A               ;Vul tabel met stringlengte
                INC DE
                DJNZ MTB1
                LD D,B
                LD E,A
                ADD HL,DE               ;[HL] = einde van de zoekstring
                LD B,A                  ;[B] = lengte van de zoekstring
                DEC HL
                DEC B                   ;Laatste teken doet niet mee met
                RET Z                   ; verschuiven
                LD C,1                  ;[C] = positie van het teken in
MTB2:           PUSH HL                 ;  zoekstring
                LD E,(HL)
                LD HL,DISKBUF           ;Ga naar positie van teken [E] in tabel
                ADD HL,DE
                LD A,(HL)               ;Kijk welke positie er stond
                CP C                    ;Oude pos < Pos van huidige teken?
                JR C,MTB3               ; Ja, => Teken bestaat al in de str.
                LD (HL),C               ; Nee, teken komt voor 1e keer voor
MTB3:           POP HL
                DEC HL
                INC C
                DJNZ MTB2               ;Verwerk volgende teken uit zoekstring
                RET

                ;Bepaal positie van ZOEKBUF in STRBUF

POS:            XOR A                   ;Begin zoeken op 1e pos in STRBUF
POS2:           LD HL,(ZOEKBUF)         ;Entry2: Zoek vanaf pos [A]
                ADD A,L                 ;Achteruit zoeken
                LD D,0
                LD E,L
                LD HL,ZOEKBUF
                ADD HL,DE               ;Bereken eindadres van zoekbuffer
                PUSH HL

SLP1:           LD (INDEX),A            ;Index = Positie in tekst
                LD D,0
                LD E,A
                LD HL,STRBUF
                DEC A
                CP (HL)                 ;Is tekst korter dan begin index?
                LD A,D
                JR NC,POS3              ; Ja, terug met A=0
                ADD HL,DE               ;Bereken indexadres in tekst
                POP DE                  ;[DE]=Eindadres van zoekbuffer
                PUSH DE                 ;[HL]=Pos in tekst
                LD A,(ZOEKBUF)          ;[B] =Lengte zoekstring
                LD B,A
                LD C,(HL)               ;C=Teken op pos. index
                EX DE,HL
SLP2:           LD A,(DE)               ;Haal teken uit tekst
                BIT BOVONDK,(IY-FLAGS3) ;Verschil klein/hoofdletter?
                CALL Z,KLEIN            ; Nee, maak klein
                CP (HL)                 ;Tekens gelijk?
                JR NZ,POS4              ; Nee, => Stop op deze index
                DEC HL
                DEC DE
                DJNZ SLP2
                LD HL,(ZOEKBUF)
                LD A,(INDEX)
                SUB L                   ;Bereken begin positie van gevonden
                INC A                   ; woord
                LD (INDEX),A
POS3:           POP DE
                RET                     ;Gevonden
POS4:           LD A,C                  ;[A] wordt teken op positie INDEX
                BIT BOVONDK,(IY-FLAGS3) ;Verschil klein/hoofdletter?
                CALL Z,KLEIN            ; Nee, maak klein
                LD B,0
                LD C,A
                LD HL,DISKBUF           ;Haal op te schuiven posities uit tabel
                ADD HL,BC               ;Als het teken niet in het zoekwoord
                LD B,(HL)               ; voorkomt wordt er een woordlengte
                LD A,(INDEX)            ; vooruit gesprongen
                ADD A,B                 ;Verhoog index met [B] posities
                JR NC,SLP1              ; Geen overflow, => Zoek verder
                XOR A                   ; Overflow, regeleinde bereikt.
                POP DE
                RET

                ;Bewaar/laad huidige instellingen

SAVINS:         CALL EVTOPSLAAN         ;Bewaar huidige regel
                LD HL,TSAVINS
                LD C,5
                CALL INVOER             ;Toon bewaar menu
SVLOOP:         LD L,(IY+MINLIN)
                LD H,53
                BIT SVINS,(IY+SAVFL2)   ;Zet cursor op bovenste regel, kol 53
                CALL AANCSR             ;Toon bewaar inst. aan/uit
                LD HL,TKEUZE
                CALL MESSAGE
                LD HL,INSADR
                LD BC,INSKAR
                LD A,1                  ;Cursor aan
                JP GETCMD               ;Haal toets en voer cmd uit

                ;F2/B jumptable

INSADR:         dw ESCAPE
                dw CHELKE               ;Elke tekst bewaren
                dw SAVDEF               ;Bewaar in TED
                dw SAVINSFILE           ;Bewaar instellingen
                dw LDINSFILE            ;Laad instellingen

CHELKE:         LD A,(IY+SAVFL2)
                XOR 1 SHL SVINS         ;Inst. Wel/Niet bij elke tekst bewaren
                LD (IY+SAVFL2),A
                JR SVLOOP               ;Terug naar hoofdlus

SAVINSFILE:     call toCurLine          ; Ja, bouw scherm op
                LD HL,TSAVNAM
                BIT DOS2,(IY-FLAGS5)    ;DOS2 pathname?
                JR Z,SA2
                INC HL                  ; Ja, sla de 3 tabs over
                INC HL
                INC HL
SA2:            LD C,1
                CALL INVOER             ;Haal bestandsnaam
                CALL NAAM
                RET C
SAVINSE:        LD HL,TMOMENT           ;Entry voor SAVE
                CALL MESSAGE            ;Momentje...
                CALL SAVCOL             ;Bewaar kleur palette
                BIT DOS2,(IY-FLAGS5)    ;DOS2 aanwezig?
                JR Z,SA3                ; Nee, => maak FCB
                LD HL,BUF
                LD DE,path1Buf          ;Copieer path/filenaam naar BUF+125
                LD BC,65
                LDIR
                CALL MAKETED            ;Maak extensie .TED
                LD DE,path1Buf+1
                LD BC,CREATEFH          ; Ja, create file handle
                LD A,10B                ;Write only
                CALL DOS
                JP NZ,TOOMANY           ; => Too many files
                LD (IY+DSKFLG),B        ;Bewaar filehandle
                LD DE,STARTVAR
                LD HL,TOINHOUD-STARTVAR ;HL=Lengte
                LD C,WRITEFH
                CALL DOS                ;Schrijf data naar het bestand
                JP NZ,DISKVOL
                JP CLOSEBF              ;Sluit de filehandle
SA3:            LD HL,SA3B
                PUSH HL
                LD DE,FCB
                PUSH DE
                LD HL,FCB1              ;Haal naam op
                LD BC,9
                LDIR
                LD HL,TTED
                LD BC,3
                LDIR                    ;Vul .TED extensie in
                LD A,CREATE
                PUSH AF                 ;Bewaar DOS-open/create
                JP MKF0                 ;Maak het FCB
SA3B:           RET C                   ; Too many files => RET
                LD DE,STARTVAR
                LD C,SETDMA             ;Zet startadres
                CALL DOS
                LD HL,TOINHOUD-STARTVAR ;HL=Lengte
                LD DE,FCB
                LD C,RBWRITE
                CALL DOS
                OR A
                JP NZ,DISKVOL
                JP CLOSEBF              ;Sluit het FCB

ldInsFile:      call toCurLine          ;Laad instellingen file
                ld hl,tLoadNam
                bit dos2,(iy-flags5)    ;DOS2 pathname?
                jr z,sa5
                inc hl                  ; Ja, sla de 3 tabs over
                inc hl
                inc hl
sa5:            ld c,1
                call invoer             ;Haal bestandsnaam
                call naam
                ret c
                call loadIns            ;Laad instellingen
                jp chkPageTab           ;Controleer op illegale paginastops

loadIns:        SET MTED,(IY-FLAGS5)    ;Maak entry: maak extensie .TED
loadIn2:        LD HL,TMOMENT
                CALL MESSAGE            ;Momentje...
                BIT DOS2,(IY-FLAGS5)    ;DOS2 aanwezig?
                JR Z,SA6                ; Nee, => open FCB
                LD HL,BUF
                LD DE,path1Buf          ;Copieer path/filenaam naar BUF+125
                LD BC,65
                LDIR
                BIT MTED,(IY-FLAGS5)
                CALL NZ,MAKETED         ;Maak extensie .TED
                LD DE,path1Buf+1
                LD C,OPENFH             ; Ja, open file handle
                LD A,1                  ;Read only
                CALL DOS
                RET NZ                  ; => Niet gevonden
                LD (IY+DSKFLG),B
                LD HL,TVERSIE-STARTVAR
                CALL CHKVER             ;Kijk of het ted 2.5 bestand is
                JR Z,SA5B               ; Ja, => Ok
                LD A,B
                CP 3                    ;Eerste cijfer ok? (versie 2.xx?)
                JP Z,VERSERR            ; Nee, => Onleesbaar
SA5B:           XOR A                   ; Ja, lukt wel, alleen hulpscherm niet
                LD H,A
                LD L,A
                LD D,A
                LD E,A
                LD B,(IY+DSKFLG)
                LD C,SEEK
                PUSH BC
                CALL DOS                ;File pointer op nul
                POP BC
                BIT MSXK,(IY+SAVFL)
                PUSH AF                 ;Bewaar MSX-set stand
                BIT STTAB,(IY+TABSAV)   ;Tabs in geheugen j/n
                PUSH AF                 ;Vlag bewaren
                LD A,(IY+BOTMAP)        ;Bewaar huidige aantal vram pagina's
                PUSH AF
                LD DE,STARTVAR
                LD HL,TOINHOUD-STARTVAR ;HL=Lengte
                LD C,READFH
                CALL DOS                ;Lees de instellingen uit het bestand
                JR SA8                  ; => Bouw scherm op + sluit het bestand
SA6:            LD DE,FCB               ;FCB adres
                LD HL,FCB1              ;Haal naam op
                LD BC,9
                LDIR
                BIT MTED,(IY-FLAGS5)
                JR Z,SA6B
                LD HL,TTED
SA6B:           LD BC,3                 ;Vul .TED extensie in

                ldir                    ;Verplaats extensie naar FCB
                xor a
                ld (de),a               ;Wis extentbyte van FCB
                ld c,open
                ld de,fcb
                call dos                ;Open file
                or a
                ret nz                  ; => error

                ld hl,1
                ld (grootte),hl
                ld (iy+dskflg),L        ;1 File open
                dec hl
                ld (blok),hl
                ld (blok+2),hl

                LD HL,TVERSIE-STARTVAR
                CALL CHKVER             ;Kijk of het ted 2.4 bestand is
                JR Z,SA7B               ; Ja, => Ok
                LD A,B
                CP 3                    ;Eerste cijfer fout? (niet 2.xx?)
                JP Z,VERSERR            ; Ja, => Onleesbaar
SA7B:           LD DE,STARTVAR          ; Nee, lukt wel, alleen hulpscherm niet
                LD C,SETDMA
                CALL DOS
                LD HL,0
                LD (BLOK),HL
                LD (BLOK+2),HL
                BIT MSXK,(IY+SAVFL)
                PUSH AF                 ;Bewaar MSX-set stand
                BIT STTAB,(IY+TABSAV)   ;Tabs in geheugen j/n
                PUSH AF                 ;Vlag bewaren
                LD A,(IY+BOTMAP)        ;Bewaar huidige aantal vram pagina's
                PUSH AF
                LD A,(IY+MAPFLAG)       ;Bewaar huidige mapper stand.
                PUSH AF
                LD HL,TOINHOUD-STARTVAR ;HL=Lengte
                LD DE,FCB
                LD C,RBREAD
                call dos                ;Lees de instellingen uit het bestand
                pop bc
                ld (iy+mapFlag),b
sa8:            pop bc
                LD (IY+BOTMAP),B
                pop af                  ;Stonden er TAB's in het geheugen?
                jr z,noTabsInMem        ; Nee, => TAB stand uit .TED file is Ok
                ld hl,(lastLine)        ;Staat er tekst in het geheugen?
                ld a,h
                or l
                jr z,noTabsInMem        ; Nee, => TAB stand niet herstellen
                set sttab,(iy+tabSav)   ; Ja, TAB-vlag terug voor `get' routine
noTabsInMem:    ld hl,'5.'              ;Maak het versienummer weer 2.5
                ld (tVersie+1),hl       ; bij inladen van een 2.4 ins. file
                call closeBf            ;Sluit het FCB/File handle
                call resetBlok          ;Wis blok-definities
                call iniClr             ;Stel scherm in
                pop af
                ret nz                  ;Klaar indien MSX set aan stond
                bit msxK,(iy+savFl)     ;Staat MSX-Karset nu wel aan?
                call nz,msxKar          ; Ja, kopieer de set uit ROM
                ret

                ;Maak dos2 extensie .TED

MAKETED:        LD DE,path1Buf+1        ;Pathname in DE
                LD BC,PARSE             ;Parse pathname
                CALL DOS
                BIT 4,B                 ;Extensie aanwezig?
                JR Z,MA2
MA1:            LD A,(HL)               ; Ja, zoek de '.'
                INC HL
                CP '.'
                JR NZ,MA1
                DEC HL
                EX DE,HL
MA2:            EX DE,HL
                LD (HL),'.'             ;Maak extensie .TED
                INC HL
                LD (HL),'T'
                INC HL
                LD (HL),'E'
                INC HL
                LD (HL),'D'
                INC HL
                LD (HL),0
                RET

                ;Kontroleer versie nummer van instellingenbestand, HL=File pos.

CHKVER:         LD DE,0
                BIT DOS2,(IY-FLAGS5)    ;DOS2?
                JR NZ,CHV1
CHKVER1:        LD (BLOK+2),DE          ; Nee, vul FCB rec. nummer in
                LD (BLOK),HL
                LD DE,DISKBUF
                LD C,SETDMA
                CALL DOS
                LD DE,FCB
                LD HL,3                 ;Haal 3 bytes
                LD C,RBREAD
                CALL DOS
                OR A
                JR CHV2
CHV1:           LD C,SEEK               ;Dos2 entry
                LD B,(IY+DSKFLG)
                XOR A
                PUSH BC
                CALL DOS                ;Zet file-pointer op versienummer
                POP BC
                LD DE,DISKBUF
                LD HL,3
                LD C,READFH
                CALL DOS                ;Lees versienummer in diskbuf
CHV2:           RET NZ                  ; Mislukt
                LD HL,TVERSIE
                LD DE,DISKBUF
                LD B,3
CHV3:           LD A,(DE)               ;Goede TED.COM versie?
                CP (HL)
                RET NZ                  ; Nee, => Close
                INC HL
                INC DE
                DJNZ CHV3
                RET

                ;Bewaar kleuren in systeem gebied

SAVCOL:         LD A,1                  ;Haal kleurnummers
SC1:            PUSH AF
                CALL GETPLT             ;Haal palette
                POP AF
                PUSH AF
                LD HL,COLORS-2
                ADD A,A                 ;2 bytes per kleur (1.5 nibble)
                LD D,0
                LD E,A
                ADD HL,DE               ;Bereken pos. in kleurtabel
                LD (HL),B               ;Bewaar rood en blauw
                INC HL
                LD (HL),C               ;Bewaar groen
                POP AF
                INC A
                CP 5                    ;Tot kleur 5
                JR C,SC1
                RET

SAVDEF:         CALL SAVCOL             ;Haal kleurnummers
                LD HL,DEFFCB
                LD DE,FCB
                LD BC,DEFEND-DEFFCB
                LDIR                    ;Vul TED.COM in in FCB
                LD DE,FCB
                LD C,OPEN
                CALL DOS
                OR A
                JP NZ,NOTFOUND          ;TED.COM niet gevonden...
                LD HL,1
                LD (GROOTTE),HL
                LD HL,TVERSIE-100H      ;Controleer versie
                LD DE,0
                CALL CHKVER1
                JR NZ,SDF3              ;Foute versie => Error
                LD DE,STARTVAR
                LD C,SETDMA             ;Zet startadres
                CALL DOS
                LD HL,SDF2
                PUSH HL
                LD HL,(TOCHK)
                JP (HL)                 ;Controleer checksum
SDF2:           LD HL,STARTVAR-100H     ;Schrijf in pos STARTVAR
                LD (BLOK),HL
                LD HL,ENDVAR-STARTVAR   ;HL=Lengte
                LD DE,FCB
                LD C,RBWRITE
                CALL DOS
                OR A
SDF3:           JP NZ,VERSERR           ;Verkeerde TED versie
                LD DE,FCB
                LD C,CLOSE
                JP DOS

                ;Markeer begin van een blok

STARTBLOK:      LD HL,(CSRNUM)
                LD (BSTARTLN),HL
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)
                DEC A
                LD (IY-BSRTPOS),A       ;Xpos 1e regel
STB1:           JP SETBOUW              ;Toon het blok

                ;Markeer einde van een blok

ENDBLOK:        LD HL,(CSRNUM)
                LD (BENDLN),HL
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)
                DEC A
                LD (IY-BENDPOS),A       ;Xpos laatste regel
                JR STB1

                ;Wis blok definitie

RESETBLOK:      LD HL,0
                LD (BSTARTLN),HL
                LD (BENDLN),HL
                LD (IY-BSRTPOS),L
                LD (IY-BENDPOS),L
                JR STB1

                ;Kopi‰er een blok

COPYBLOK:       RES MOVE,(IY-FLAGS4)    ;Wis blokverplaats vlag
                LD HL,(BSTARTLN)
                LD DE,(BENDLN)
                CALL DCOMPR             ;Is blok aanwezig?
                JR C,CPB
                JP NZ,BEEP
                LD A,(IY-BSRTPOS)
                SUB (IY-BENDPOS)
                JP NC,BEEP              ; Nee, => Terug
CPB:            EX DE,HL
                LD HL,(CSRNUM)
                CALL DCOMPR             ;Cursor in blok?
                JR C,CPD                ; Nee, => CPD
                JR NZ,CPC
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)
                DEC A
                CP (IY-BSRTPOS)
                JR C,CPD
                JR Z,CPD
CPC:            LD DE,(BENDLN)
                CALL DCOMPR
                JP C,BEEP
                JR NZ,CPD
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)
                DEC A
                CP (IY-BENDPOS)
                JP C,BEEP               ; Ja, => Niet inzichzef kopieeren

cpD:            ld hl,tMoment
                call message            ;Momentje...
                set dispOff,(iy-flags5) ;Niet scrollen etc.
                ld hl,0
                ld (curBReg),hl         ;Huidige regel in blok = 0
                ld a,(iy+savFl2)
                push af
                ld a,(iy+tabSav)
                push af
                res uitVul,(iy+tabSav)  ;Niet uitvullen
                res edit,(iy+savFl2)    ;Geen spaties weghalen
                call retIns             ;Breek doelregel in 2en
                pop af
                ld (iy+tabSav),a
                pop af
                ld (iy+savFl2),A
                call opslaan            ;Bewaar regel
                ld hl,(csrNum)
                ld (movSrt),hl          ;Start van nieuwe blok (voor MOVEBLOK)
                dec hl
                ld (csrNum),hl          ;Van te voren 1 te laag

                LD HL,(BENDLN)
                LD DE,(BSTARTLN)
                OR A
                SBC HL,DE               ;Bereken aantal regels
                LD (MOVLEN),HL          ;Bewaar voor MOVEBLOK
CPE:            LD DE,(BSTARTLN)        ;Haal nummer
                LD HL,(CURBREG)
                ADD HL,DE
                EX DE,HL
                LD HL,STRBUF
                CALL GET                ;Haal regel op
                LD HL,(CSRNUM)          ;Haal bestemming op
                INC HL
                LD (CSRNUM),HL          ;Verhoog bestemmingsregel
                CALL ADDLINE            ;Regel tussenvoegen
                LD HL,(CURBREG)
                INC HL                  ;Verhoog blokregel
                LD (CURBREG),HL
                LD DE,(BSTARTLN)
                ADD HL,DE
                EX DE,HL
                LD HL,(BENDLN)
                CALL DCOMPR             ;Klaar?
                JR NC,CPE               ; Nee, => Volgende regel
                LD H,(IY-BSRTPOS)
                PUSH HL                 ;Bewaar start- & endpos
                LD B,(IY-BENDPOS)
                PUSH BC
                BIT MOVE,(IY-FLAGS4)    ;Blok verplaatsen?
                JP NZ,MOVE2             ; Ja, => terug

COPMOV:         POP BC                  ;2e entry voor moveblok
                LD (IY+OFFSET),0
                INC B
                LD (IY+XPOS),B          ;Zet cursor op blokeinde
                DEC B
                LD A,(STRBUF)
                SUB B                   ;Reglen-blokeinde is teveel gekopi‰erd
                JR NC,CPF
                XOR A
CPF:            INC A                   ;1 keer extra deleten zodat regels weer
                LD B,A                  ; aan elkaar geplakt worden.
CPG:            PUSH BC
                CALL DELETE
                POP BC
                DJNZ CPG
                CALL OPSLAAN
                LD HL,(MOVSRT)
                LD (CSRNUM),HL          ;Weer terug naar startregel
                EX DE,HL
                LD HL,STRBUF
                CALL GET
                POP BC                  ;Haal startpos.
                INC B                   ;1 keer extra backspacen
                LD (IY+OFFSET),0
                LD (IY+XPOS),B          ;Zet cursor op blokbegin
                res vir,(iy-flags6)     ;Geen virtuele cursor meer
CPH:            push bc
                call bSpace
                pop bc
                djnz cpH
                call opslaan
                res dispOff,(iy-flags5) ;Maak schermopbouw weer actief
                ld hl,(csrNum)
                jp goLine2              ;Klaar


; wisBlok
;
; Wist een gemarkeerd tekstblok
;
wisBlok:        call zeker              ;Zeker weten?
                ret c                   ; Nee, => Terug
                call evtOpslaan
                set sav,(iy+flags1)     ;Saven voor stoppen
                res move,(iy-flags4)    ;Niet aangeroepen door MoveBlok

                ld hl,tMoment
                call message            ;Momentje...

wb2:            ld hl,(bStartLn)
                ld de,(bEndLn)
                call dCompr             ;Is blok aanwezig?
                jr c,wb2b
                jp nz,beep
                ld a,(iy-bSrtPos)
                sub (iy-bEndPos)
                jp nc,beep              ; Nee, => Terug
wb2b:           ld (csrNum),hl

                set dispOff,(iy-flags5) ;Geen scherm opbouw, geen scroll etc.
                ld a,(iy+tabSav)
                push af
                res uitVul,(iy+tabSav)  ;Niet uitvullen
                ld (iy+offSet),0
                ld a,(iy-bSrtPos)       ;Zet cursor op start van blok
                inc a
                ld (iy+xPos),a
                ex de,hl
                ld hl,strbuf
                call get
                call retIns             ;Start van blok naar volgende regel
                call opslaan
                ld hl,(bEndLn)
                ld (csrNum),hl
                ld (iy+offset),0
                ld a,(iy-bEndPos)       ;Zet cursor op einde van blok
                inc a
                ld (iy+xPos),a
                ex de,hl
                ld hl,strBuf
                call get
                call retIns             ;Einde van blok naar volgende regel
                ld (iy-bEndPos),0       ; en zet alvast op nul
                call opslaan
                pop af
                ld (iy+tabSav),a        ;Herstel uitvul-vlag

                ld de,(bStartLn)        ;Begin vooraan blok

delFirstLine:   push de                 ;Bewaar blokbegin
                push de                 ;Bewaar huidige regel

                call zoekNum            ;Zoek eerste regel
                pop de                  ;Haal huidige regel
                jp c,delBlkDone         ; => Klaar

                push de                 ;Bewaar huidige regel

                ld (iy-firstDataSeg),-1 ;Eerste datasegment nog onbekend

                ld de,0                 ;Aantal te wissen pointers
                ld (aantDelPnt),de

                ld (firstPntAddr),ix    ;Adres van eerste pointer

                ld a,(iy+curTab)        ;Haal pointersegment
                ld (iy-firstPntSeg),a

                jr chkLineData          ;Zet string-data adressen

chkDelLineLp:   inc de
                push de                 ;Te verwijderen regel in DE
                call zoekNum            ;Zoek regel op in datageheugen
                jr c,delBlock           ; Laatste regel, => Wis blok

chkLineData:    inc c
                dec c                   ;Stringlengte 0?
                jr z,chkPointer         ; Ja, => Alleen pointerseg. controleren

                ld a,(iy-firstDataSeg)  ;Is er al een datasegment bekend?
                inc a
                jr nz,chkDataAddr       ; Ja, => Contreer of het adres aansluit

                ld a,(iy+curMap)        ; Nee, haal datasegment
                ld (iy-firstDataSeg),a

                ld (firstDataAddr),hl   ;Zet startadres van eerste string

                jr endDataChk           ;Bereken adres van volgende string

chkDataAddr:    ld a,(iy+curMap)
                cp (iy-firstDataSeg)    ;Datasegment hetzelfde?
                jr nz,delBlock          ; Nee, => Wis blok met regels

                ld de,(nextDataAddr)    ;Aansluitende string?
                call dCompr
                jr nz,delBlock          ; Nee, => Wis voorgaande blok

endDataChk:     ld a,(iy+curTab)        ;Haal huidige pointersegment
                cp (iy-firstPntSeg)     ;Gelijk aan vorige segment?
                jr nz,delBlock

                add hl,bc               ; Ja, bereken adres waar volgende
                ld (nextDataAddr),hl    ;  string moet starten

                jr incPointer

chkPointer:     ld a,(iy+curTab)        ;Haal huidige pointersegment
                cp (iy-firstPntSeg)     ;Gelijk aan vorige segment?
                jr nz,delBlock

incPointer:     ld hl,(aantDelPnt)      ;Verhoog aantal te wissen pointers
                inc hl
                ld (aantDelPnt),hl

                pop de                  ;Haal huidige regelnr.

chkEndBlk:      ld hl,(bEndLn)
                call dCompr             ;Blokstart=Blokeinde?
                jr nz,chkDelLineLp      ; Nee, => Controleer volgende aansluit

                ld hl,(aantDelPnt)      ;Aantal te verwijderen regels
                ld a,h
                or l
                jr z,delBlkDone         ; Nul, => Klaar

                push de                 ;Dummy, voorkom stack underflow

delBlock:       pop de                  ;Haal huidige regel
                ld hl,(bEndLn)          ;Haal laatste regel
                or a
                sbc hl,de               ;Zoveel regels nog te wissen
                call regNum             ;Toon aantal nog te wissen regels

                pop de                  ;Haal blokbegin
                push de                 ;Bewaar blokbegin

                ld bc,delBlkRet
                push bc                 ;Bewaar retaddr

                ld bc,(firstDataAddr)   ;Haal en bewaar
                push bc                 ; stringdata startadres

                ld l,(iy-firstDataSeg)  ;Haal data-segment?
                inc l                   ;Geldig segment? (-1 = ongeldig)
                ld h,l                  ;   Stel datalengte [HL] alvast op 0
                jr z,delPntOnly         ; Nee, => Alleen pointers wissen

                ld hl,(nextDataAddr)    ; Ja, bereken aantal te wissen bytes
                or a
                sbc hl,bc               ;Bereken stringlengte in HL
delPntOnly:     push hl                 ;Bewaar stringlengte

                ld hl,(firstPntAddr)
                push hl                 ;Pointer adres

                ld a,(iy-firstPntSeg)
                ld (iy+curTab),a
                call mmOut              ;Pointersegment inschakelen

                ld a,(iy-firstDataSeg)
                ld (iy+curMap),a        ;String datasegment

                ld hl,(aantDelPnt)      ;Aantal te wissen regels
                jp delLines             ;Wis de regels

delBlkRet:      pop de                  ;Haal blokbegin

                ld hl,(bEndLn)
                inc hl
                call dCompr             ;Blokstart=Blokeinde+1?
                jp nz,delFirstLine      ; Nee, => Begin nieuw blok

                push de                 ; Klaar, dummy op stack

delBlkDone:     pop hl                  ;Verwijder blokbegin
                ld hl,(bEndLn)
                inc hl
                call gotoLine
                call resetBlok          ;Blokdefinitie weg
                call bSpace             ;Plak eind weer aan begin
                bit move,(iy-flags4)    ;Aangeroepen door blok-verplaats?
                ret nz                  ; Ja, => Scherm nog niet opbouwen
                res dispOff,(iy-flags5) ; Nee, maak schermopbouw weer actief
                ret


; moveBlok
;
; Verplaats een blok
;
MOVEBLOK:       LD HL,(BSTARTLN)
                LD DE,(BENDLN)
                CALL DCOMPR             ;Is blok aanwezig?
                JR C,MB1
                JP NZ,BEEP
                LD A,(IY-BSRTPOS)
                SUB (IY-BENDPOS)
                JP NC,BEEP              ; Nee, => Terug
MB1:            EX DE,HL
                LD HL,(CSRNUM)
                CALL DCOMPR             ;Cursor in blok?
                JR C,MB2                ; Nee, => MB2
                JR NZ,MB1B
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)
                DEC A
                CP (IY-BSRTPOS)
                JR C,MB2
                JR Z,MB2
MB1B:           LD DE,(BENDLN)
                CALL DCOMPR
                JP C,BEEP
                JR NZ,MB2
                LD A,(IY+XPOS)
                ADD A,(IY+OFFSET)
                DEC A
                CP (IY-BENDPOS)
                JP C,BEEP               ; Ja, => Niet inzichzef kopieeren
MB2:            SET MOVE,(IY-FLAGS4)    ;Vlag voor copyblok
                JP CPD                  ;Kopi‰er naar cursor

MOVE2:          LD HL,(MOVSRT)          ;Entry na blok-copy
                LD DE,(BSTARTLN)
                PUSH HL
                OR A
                SBC HL,DE               ;Cursor na blok?
                PUSH AF                 ; Ja, => F=NC
                CALL WB2                ;Wis oude blok
                CALL OPSLAAN            ;Laatste regel bewaren
                POP AF
                POP HL
                LD BC,(MOVLEN)
                JR C,MB3                ;Cursor niet opschuiven
                OR A
                SBC HL,BC               ;Cursor omhoog omdat blok gewist is
MB3:            LD (BSTARTLN),HL
                LD (MOVSRT),HL
                LD (IY-BSRTPOS),0
                INC BC
                ADD HL,BC               ;Ga naar einde van blok
                LD (BENDLN),HL
                LD (IY-BENDPOS),0       ;Vul blokeinde pos in.
                DEC HL
                CALL GOTOLINE
                JP COPMOV               ;Maak copy af


; IndentBlok
;
; F5/Inspring
; Verschuif tekstregels naar rechts of links
;
indentBlok:     call evtOpslaan
                ld hl,tIndent
                ld c,3
                call invoer             ;Toon indent menutje

indMenuLp:      ld l,(iy+minLin)
                ld h,xAantPos           ;Haal x-pos op van "aantal"-tekst
                ld (csry),hl
                ld a,(iy+aantIndent)    ;Inspringafstand
                or a                    ;Nul? (kan ook bij oude .TED file)
                jr nz,indNotZero
                inc a                   ; Ja, veranderen in 1
                ld (iy+aantIndent),a
indNotZero:     call bcdSet             ;Toon inspring afstand

                ld hl,tKeuze
                call message
                ld hl,indAdr
                ld bc,indKar
                ld a,1                  ;Toon csr
                call getCmd             ;Wacht op toets
                jr indMenuLp            ;En toon nieuwe instellingen


; F5/Inspring jumptable
;
indAdr:         dw menuESC              ;ESCape
                dw setIndPos            ;Aantal posities aanpassen
                dw doLeftInd            ;Inspringen naar links
                dw doRightInd           ;Inspringen naar rechts

setIndPos:      ld d,xAantPos           ;External, LD DE,256*x mag niet
                ld e,0
                call menuXY             ;Locate x,0
                ld a,(iy+aantIndent)
                call getONr             ;Haal inspring-getal
                ret z
                ld (iy+aantIndent),l
                ret

; Schuif naar links
;
doLeftInd:      set indDir,(iy+savFl3) ;Inspringrichting = links
                jr doIndent

; Schuif naar rechts
;
doRightInd:     res indDir,(iy+savFl3) ;Inspringrichting = rechts

; Voer blokverschuifactie uit
;
doIndent:       pop hl                  ;Verwijder returnadres naar menulus

                ld (iy-bSrtPos),0       ;Zet blokstart op nul
                ld hl,(bEndLn)
                ld a,(iy-bEndPos)
                or a                    ;Xpos blokeinde > 1e teken?
                jr z,chkIndBlk
                inc hl                  ; Ja, verhoog laatste regel met 1
                ld (bEndLn),hl
                ld (iy-bEndPos),0

chkIndBlk:      set sav,(iy+flags1)     ;Saven voor stoppen

                ld de,(bStartLn)
indentLp:       ld hl,(bEndLn)
                scf                     ;Blokeinde 1 reg. na eind van blok
                sbc hl,de               ;HL=Aantal regels
                jp c,toCurLine          ;Laatste regel gedaan

                push de                 ;Bewaar huidige regel
                call regNum             ;Toon HL = aantal regels te gaan

                pop de                  ;DE=Huidige regel
                push de
                ld hl,strBuf            ;HL=Opslagbuffer, lowbyte = 0
                call get                ;Haal regel

                ld a,(hl)               ;Haal stringlengte, max 254
                or a                    ;Lege regel?
                jr z,indNextLine        ; Ja, => Deze overslaan

                bit indDir,(iy+savFl3)  ;Spaties invoegen of verwijderen?
                jr nz,moveToLeft        ; => Verwijderen

                ld c,a                  ;Lengte onthouden in c
                inc a                   ;Makkelijker test op overflow
                add a,(iy+aantIndent)   ;Aantal toe te voegen spaties erbij
                jr nc,noIndOverflow     ; => Geen overflow
                ld a,255                ;Overflow, regel wordt Maxlengte+1
noIndOverflow:  dec a                   ;Herstel lengte
                ld e,a                  ;Onthouden in E
                sub (hl)                ;Bereken aantal toe te voegen spaties
                jr z,indNextLine        ;Regel vol => Volgende regel
                ld (hl),e               ;Nieuwe lengte invullen
                ld d,high strBuf        ;DE = Nieuwe einde van de regel
                ld l,c                  ;HL = Oude einde van de regel
                ld b,0                  ;BC = Oude lengte van de regel
                lddr                    ;Regel naar rechts schuiven
indAddSpace:    inc hl                  ;Naar 1e teken, skip lengtebyte
                ld (hl),' '             ;Ruimte opvullen met spaties
                dec a                   ;A is aantal spaties
                jr nz,indAddSpace

indStoreLine:   pop de                  ;Haal regelnummer
                push de
                ld hl,strBuf
                call put                ;Bewaar regel
indNextLine:    pop de
                inc de                  ;Naar volgende regel
                jr indentLp

moveToLeft:     ld c,a                  ;Regellengte in C
                ld b,(iy+aantIndent)    ;Aantal te wissen spaties
                ld d,0                  ;Aantal gevonden spaties
indTstSpc:      inc hl
                ld a,(hl)               ;Staat er wel een spatie aan
                cp ' '                  ; regelbegin?
                jr nz,indNoSpc          ; Nee, => Wissen tot hier
                inc d                   ;Aantal gevonden spaties
                djnz indTstSpc
                inc hl                  ;Naar 1e karakter na spaties

indNoSpc:       inc d                   ;Nul spaties gevonden?
                dec d
                jr z,indNextLine        ; Ja, => Niets wissen

                ld a,c                  ;Regellengte
                sub d                   ;Bereken nieuwe regellengte
                ld (strBuf),a           ;Invullen
                jr z,indStoreLine       ;Regel leeg => Klaar

                ld b,0                  ;Regellengte in BC
                ld c,a
                ld de,strBuf + 1        ;Regelstart in DE
                ldir                    ;Spaties wissen
                jr indStoreLine         ;Regel opslaan


                ;Print regelnummer HL

REGNUM:         EX DE,HL
REGNUMDE:       LD HL,VRMREG            ;Locate 18,0
                CALL NSTWRT
                EX DE,HL
                PUSH HL
                INC HL
                CALL DECI               ;Zet regelnummer op scherm
                POP HL
                RET

                ;Voeg schermregel tussen

INSREG:         bit dispOff,(iy-flags5) ;Scherm opbouw actief?
                ret nz                  ; Nee, => Geen scroll

                ld a,(iy+maxLin)
                cp (iy+yPos)            ;Onderste regel (NC=Ja)?
                bit bouw,(iy-flags4)    ; Wordt scherm al opgebouwd?
                jr nc,in2               ;    Niet onderste regel => Scroll down
                jr nz,in1               ;  Ja, => Geen scroll omlaag

                ld l,(iy+minLin)        ;Verwijder regel L (bovenste regel)

scrlUp:         bit dispOff,(iy-flags5) ;Scherm opbouw actief?
                ret nz                  ; Nee, => Geen scroll omhoog

                push af                 ;Carryflag gezet als YPOS=MAXLIN
                push hl
                ld a,(iy+maxLin)        ;Onderste regel
                sub l                   ;L=Aantal op te schuiven regels
                jr z,in0                ;Nul regels => Snel klaar
                LD HL,10
                LD D,H
                LD E,A
                CALL MUL16              ;Bereken aantal te verschuiven bytes
                LD D,H                  ;D=0
                EX (SP),HL
                LD E,L                  ;E=(IY+MINLIN)
                EX (SP),HL
                PUSH HL
                LD HL,10
                CALL MUL16              ;Bereken VRAM bronadres
                LD DE,(TXTCOL)
                ADD HL,DE
                POP BC
                PUSH BC
                PUSH HL
                LD DE,DISKBUF           ;Naar diskbuf
                XOR A
                CALL NLDRMV             ;Haal uit vram
                POP HL
                LD DE,10
                OR A
                SBC HL,DE               ;1 regel omhoog
                EX DE,HL
                POP BC
                LD HL,DISKBUF
                CALL NLDVM0             ;Zet 1 regel lager weer terug
IN0:            POP HL                  ;Haal regel in L
                CALL DELLNO             ;Wis regel L
                POP AF
IN0B:           RET NC                  ;Niet de onderste regel
IN1:            LD A,(IY+MAXLIN)        ;Csr niet te laag
                LD (IY+YPOS),A
                LD (CSRY),A
                RET
IN2:            RET NZ
                LD A,(IY+MAXLIN)
                SUB (IY+YPOS)
                JR Z,IN3
                LD HL,10
                LD D,H
                LD E,A
                CALL MUL16              ;Bereken aantal te verschuiven
                PUSH HL                 ; colorbytes
                LD HL,10
                LD D,H
                LD E,(IY+YPOS)
                DEC E
                CALL MUL16              ;Bereken VRAM bronadres
                LD DE,(TXTCOL)
                ADD HL,DE
                POP BC
                PUSH BC
                PUSH HL
                LD DE,DISKBUF           ;Naar diskbuf
                XOR A
                CALL NLDRMV             ;Haal uit vram
                POP HL
                LD DE,10
                ADD HL,DE               ;1 regel omlaag
                EX DE,HL
                POP BC
                LD HL,DISKBUF
                CALL NLDVM0             ;Zet 1 regel lager weer terug
IN3:            LD L,(IY+YPOS)
                JP INSLNO               ;Voeg regel tussen

                ;Vraag om usernaam

GETNAME:

if              not (DEMO or AUTODEMO)

                LD C,5
                LD HL,TGETNAME          ;Tekst op scherm
                CALL INVOER
                LD E,0
                LD B,40                 ;40 tekens=max
                CALL GETTXT
                LD B,0
                ADD HL,BC               ;Bereken buffer einde
                LD DE,TNAME-2           ;Vul naam achterstevoren in
                INC DE
                INC DE
                LD A,C
                CP 5                    ;Te weinig tekens?
                JP C,ERROR              ; Ja, => Terug
                LD (DE),A
                INC DE
GTC1:           LD A,(HL)
                XOR CRYPTBYTE           ;Ook coderen
                LD (DE),A
                DEC HL
                INC DE
                DEC C
                JR NZ,GTC1
                JP TOCODE               ;Naar GETCODE
endif

                ;Vermenigvuldig HL met DE, uitkomst in HL

MUL16:          LD C,L
                LD B,H
                LD HL,0
                LD A,15
MLP:            SLA E
                RL D
                JR NC,MLP1
                ADD HL,BC
MLP1:           ADD HL,HL
                DEC A
                JR NZ,MLP
                OR D
                RET P
                ADD HL,BC
                RET

                ;Deel HL door DE, Uitkomst in HL, rest in DE

DIV16:          LD C,L
                LD A,H
                LD HL,0
                LD B,16
                OR A
DVLOOP:         RL C
                RLA
                RL L
                RL H
                PUSH HL
                SBC HL,DE
                CCF
                JR C,DROP
                EX (SP),HL
DROP:           INC SP
                INC SP
                DJNZ DVLOOP
                EX DE,HL                ;DE=Rest
                RL C
                LD L,C
                RLA
                LD H,A                  ;HL=Quotient
                OR A
                RET

                ;Decimaal ASCII naar binair in HL

DECTOBIN:       LD HL,0
                LD DE,BUF
                LD A,(DE)
                OR A
                RET Z
                LD B,A                  ;B=lengte
                INC DE
DB1:            LD A,(DE)
                SUB '0'
                PUSH DE
                LD D,H
                LD E,L
                ADD HL,HL
                ADD HL,HL
                ADD HL,DE
                ADD HL,HL
                LD E,A
                LD D,0
                ADD HL,DE
                POP DE
                INC DE
                DJNZ DB1
                RET

                ;Zet BCD uit buffer om in binair in A

CNVBCD:         LD HL,BUF+1
                LD A,(BUF)
                LD B,A
                LD C,0                  ;C=Honderdtallen
                OR A
                SCF
                RET Z
                CP 4
                CCF
                RET C
                LD A,B
                CP 3
                JR C,CB3                ;Geen honderdtallen ?
                LD A,(HL)
                CP '3'
                CCF
                RET C
CB1:            LD A,(HL)
                CP '0'
                JR Z,CB2
                LD A,100
                ADD A,C
                LD C,A
                DEC (HL)
                JR CB1
CB2:            INC HL
CB3:            LD D,0                  ;D=Tien+honderdtallen
                LD A,B                  ;Geen tientallen ?
                CP 2
                JR C,CB4
                LD A,(HL)
                SUB '0'
                SLA A
                SLA A
                SLA A
                SLA A
                LD D,A
                INC HL
CB4:            LD A,(HL)
                SUB '0'
                ADD A,D
                LD B,A                  ;Zet BCD om
                AND 0F0H
                RRCA
                LD D,A
                RRCA
                RRCA
                ADD A,D
                LD D,A
                LD A,B
                AND 0FH
                ADD A,D                 ;Tientallen erbij
                ADD A,C                 ;Honderdtallen erbij
                RET

                ;Print HL als decimaal getal

DCSET:          CALL SETVDP             ;Zet vdp ready
DECI:           OR A                    ;NC=Print op scherm
                JR DECI3
DECI2:          SCF                     ;Alleen in DCBUF
DECI3:          PUSH AF
                LD DE,DCBUF
                LD B,5
                LD A,' '
DC1:            LD (DE),A               ;Wis de buffer
                INC DE
                DJNZ DC1
DC2:            LD E,0
                LD B,16
                OR A
DC3:            RL L
                RL H
                RL E
                LD A,E
                SUB 10
                CCF
                JR NC,DC4
                LD E,A
DC4:            DJNZ DC3
                RL L
                RL H
                LD A,E
                ADD A,'0'
                PUSH HL
                LD HL,DCBUF+4
                LD DE,DCBUF+5
                LD BC,5
                LDDR
                LD (DCBUF),A
                POP HL
                LD A,H
                OR L
                JR NZ,DC2
                POP AF                  ;Alleen in DCBUF?
                RET C                   ; Ja, => Klaar
                LD B,5
PRDECI:         LD HL,DCBUF
                INC HL
                LD C,(IY+VDPWRITE)
                LD A,(HL)
                CP ' '
                JR NZ,DC5
                OUT (C),A               ;Start met spatie
                DEC B
DC5:            DEC HL
DC6:            LD A,(HL)
                OUT (C),A
                INC HL
                DJNZ DC6
                LD A,' '
                OUT (C),A
                RET

                ;Print huidige filenaam in statusregel

PRTSAV:         LD L,4
                BIT COMLIN,(IY+TABSAV)
                JR NZ,PSA0
                LD L,2                  ;Naam onder commandoregel
PSA0:           LD H,40-32              ;Centreer rond pos. 40 (64 kars/2)
                LD (CSRY),HL
                CALL SETVDP             ;Zet schrijfadres
                LD HL,SAVNAM            ;HL=Bestandsnaam
                LD A,(HL)               ;Haal stringlengte
                NEG
                JR NZ,PSA0C             ;Lengte > 0 => Spatie voor en na naam
                LD B,64
                JR PSA1B                ;Lengte = 0 => Alleen lijn tekenen
PSA0C:          ADD A,63                ;A=63-A
                SRL A                   ;A=A\2
                PUSH AF
                CALL PSA1               ;Strepen voor naam
                LD A,' '
                OUT (C),A               ;En 1 spatie
                CALL PS1                ;Druk naam af
                LD A,' '
                OUT (C),A
                POP AF                  ;Strepen na naam=Strepen voor naam
                INC A                   ; plus 1 rest (na SRL A)
PSA1:           OR A
                RET Z
                LD B,A
PSA1B:          LD A,17H                ;Vul rest op met strepen
                LD C,(IY+VDPWRITE)
PSA2:           OUT (C),A
                DJNZ PSA2
                RET

                ;Print een string met lengte (HL)

PRTSTR:         CALL SETVDP
PS1:            LD A,(HL)               ;Haal buf lengte
                OR A
                RET Z
                LD B,A
PS2:            LD C,(IY+VDPWRITE)
PS3:            INC HL
                LD A,(HL)
                OUT (C),A
                DJNZ PS3
                RET

                ;Print een string op scherm uit (DE)

STROUT:         PUSH DE                 ;Haal string uit RAM i.p.v. VRAM
                CALL SETVDP             ;Zet schrijfadres
                LD HL,CSRX
                LD C,(IY+VDPWRITE)
                POP DE
STRO2:          LD A,(DE)
                INC DE
                CP NUL                  ;Klaar?
                RET Z
                CP CR
                JR Z,STRO3
                CP LF
                JR Z,STRO4              ;Regel verder
                CP TAB
                JR Z,STRO5              ;Naar tab
                OUT (C),A
                INC (HL)
                JR STRO2
STRO3:          LD A,1
                LD (CSRX),A
                JR STROUT
STRO4:          LD HL,CSRY
                INC (HL)
                JR STROUT
STRO5:          LD A,' '
                OUT (C),A
                INC (HL)
                LD A,(HL)
                DEC A
STRO6:          SUB 8                   ;Naar veelvoud van 8
                JR C,STRO5              ;Nog een spatie
                JR NZ,STRO6
                LD A,(HL)
                CP 81
                JR C,STROUT             ;Op tab aangeland
                LD (HL),1               ;Naar volgende regel
                JR STRO4

                ;Bereken VRAM adres uit (CSRY)

SETVDP:         PUSH HL
                PUSH BC
                PUSH AF
                LD A,(CSRY)
                LD B,A
                LD HL,0-80
                LD DE,80
SVD1:           ADD HL,DE               ;Bereken VRAM adres
                DJNZ SVD1
                LD A,(CSRX)
                DEC A
                LD E,A
                ADD HL,DE               ;HL=Cursoradres
                CALL NSTWRT             ;Maak vdp schrijfklaar
                POP AF
                POP BC
                POP HL
                RET

                ;Memory => VRAM, A=Pagina HL=Source DE=Dest C=Len

LDRVM2:         INC A
                CP 8                    ;Pagina 0?
                JR NZ,NLDRVM
NLDVM0:         XOR A                   ;Ja, maak A dus ook nul
NLDRVM:         LD B,C                  ;B=Lengte
                EX DE,HL
                SET 6,H                 ;Write
                CALL SETADR             ;Zet vdp klaar
                EX DE,HL
                LD C,(IY+VDPWRITE)
                OTIR                    ;(HL) => Poort
                RET

                ;VRAM => Memory, A=Pagina HL=Source DE=Dest C=Len

LDRMV2:         INC A
                CP 8                    ;Pagina 0?
                JR NZ,NLDRMV
                XOR A                   ;Ja, maak A dus ook nul
NLDRMV:         LD B,C
                RES 6,H                 ;Read
                CALL SETADR             ;Zet vdp klaar
                EX DE,HL
                LD C,(IY-VDPREAD)
                INIR
                RET

                ;Set vdp write/read

NSTWRT:         SET 6,H                 ;Write-flag
NSETRD:         XOR A                   ;Zet segment nummer op 0 (SCREEN 0 pag)
SETADR:         RES 7,H                 ;Wis "Schrijf register vlag"
                DI

                LD C,(IY-VDPCW)
                OUT (C),A               ;[A]=Scherm segment nr.

                LD A,14+128
                OUT (C),A               ;ACTIVE offset
                OUT (C),L
                OUT (C),H

             ;; EI                      ;Interrupt uit is veiliger <=> TSR's
                RET                     ; zouden de Vram pointer kunnen mollen

                ;Chput + INC(CSRX)

NCHPTI:         CALL NCHPUT
                PUSH HL
                LD HL,CSRX
                INC (HL)
                POP HL
                RET

                ;Zet teken op scherm

NCHPUT:         PUSH DE
                PUSH BC
                PUSH AF
                CALL SETVDP
                LD C,(IY+VDPWRITE)
                POP AF
                OUT (C),A
                POP BC
                POP DE
                RET

                ;Haal karakter van toetsenbord/datafile

nChGet:

if              autoDemo                ;Lees uit file indien auto-run demo

                ext AUTOFCB

                push hl                 ;Bewaar alle regs
                push de
                push bc
                bit csr,(iy+tabSav)     ;Kleuren cursor?
                jr z,chg4               ; Nee, => Toon chr(255)

                ;Zet kleuren-cursor op scherm

                ld bc,(csrY)
                call clrAdr             ;Haal adres & bitpos.
                jr z,auto_rorDone       ; Bit 7? => DP4
auto_rorLp:     srl b                   ; Nee, schuif [B] 1 pos naar rechts
                dec a                   ;Verlaag teller
                jr nz,auto_rorLp        ;Niet klaar? => Opnieuw
auto_rorDone:   LD A,C                  ;Haal colorbyte op
                PUSH AF
                PUSH HL
                XOR B                   ;Inverteer cursor
                CALL NWRVRM             ;Schrijf nieuwe colorbyte
                call chkAutoQuit        ;Kijk of <ESC> werd ingedrukt
                pop hl                  ;Haal cursoradres
                pop af                  ;Wis de cursor weer
                call nWrVrm             ;Schrijf oude byte

chg3:           LD DE,DFBUF             ;Karakter naar datafilebuffer
                LD C,SETDMA
                CALL DOS
                LD DE,AUTOFCB           ;Haal teken uit datafile
                LD HL,1
                LD C,RBREAD
                CALL DOS
                LD A,H
                OR L                    ;Niets gelezen?
                JP Z,toDos              ; Ja, => Terug naar DOS
                LD A,(DFBUF)
                POP BC                  ;Regs weer terug
                POP DE
                POP HL
                RET


CHG4:           LD A,2
                LD (ESCCNT),A           ;VT-52 <ESC> 'y' 5
                LD A,'5'
                CALL CHPUT              ;Zet cursor op het scherm
CHG5:           call chkAutoQuit        ;Toon klok, test op ESC
                LD A,1
                LD (ESCCNT),A           ;VT-52 <ESC> 'x' 5
                LD A,'5'
                CALL CHPUT
                JR CHG3

; chkAutoQuit
;
; Test in auto-run demo versie of de <ESC> toets werd ingedrukt. Indien
; dat het geval is, wordt naar DOS teruggekeerd.
; Tevens wordt gewacht tot er minstens 4/50 sec. verstreken is sinds het
; vorige karakter uit de datafile gelezen werd.
;
; Uit: A = Karakter uit datafile
;
chkAutoQuit:    call int                ;Toon klok
                call enaVdpInt          ;VDP interrupts mogelijk maken
              ;;call chsns              ;Werkt niet in autodemo-mode!
                di                      ;Voorkom dat een TSR aan de toetsen-
                ld hl,(getPnt)          ; bordbuffer gaat klooien
                ld de,(putPnt)
                ei                      ;Maar het is ook wel leuk zijn dat er
                or a                    ; af en toe iets in de buffer gezet
                sbc hl,de               ; kan worden
                jr z,noAutoQuit         ; Niets, => Haal karakter van disk
                call chGet              ;Haal teken uit buffer
                cp esc                  ;ESCape ingedrukt?
                jp z,toDos              ; Ja, => Terug naar DOS
noAutoQuit:     ld hl,autoCnt
                ld a,(hl)
                cp 4                    ;Haal wacht-teller (interrupt)
                jr c,chkAutoQuit        ;Moet minstens 4 zijn
                ld (hl),0               ;Weer op nul zetten
                ret

else                                    ;Haal karakter van toetsenbord
                CALL CHSNS              ;Teken al aanwezig?
                JP NZ,CHGET             ; Ja, => Haal direkt op
                PUSH HL                 ;Bewaar alle regs
                PUSH DE
                PUSH BC
DP2:            CALL DISPCSR            ;Toon de cursor
CHG2:           CALL INT                ;Toon klok
                CALL STOPKEY            ;Check de stoptoets (= wissel relais)
                CALL BLINK              ;Laat de cursor knipperen
                CALL CHSNS              ;Wacht op toets
                JR Z,CHG2               ; Niets, => Opnieuw
                CALL DOERACSR           ;Wis de cursor
                CALL CHGET              ;Haal teken uit buffer
                POP BC                  ;Regs weer terug
                POP DE
                POP HL
                RET
endif

                ;Laat de cursor knipperen

BLINK:          LD A,(BLKON)            ;Haal de cursor AAN tijd
                OR A
                RET Z                   ;0 => AAN laten
                BIT KNIPPER,(IY+SAVFL2) ;Staat het knipperen aan?
                RET Z                   ; Nee, => AAN laten
                LD HL,(BLKCNT)          ;Haal de huidige teller (interrupt)
                BIT CSRON,(IY-FLAGS2)   ;Staat de cursor nu AAN?
                JR Z,CSROFF             ; Nee, => Kijk of hij weer AAN moet
                CP L                    ;Moet de csr UIT?
                RET NC                  ; Nee, => Hij mag nog even aan
                JR ERACSR               ;Wis de csr.
CSROFF:         LD A,(BLKOFF)           ; Nee, haal cursor uit tijd
                CP L                    ;Moet de csr weer AAN?
                RET NC                  ; Nee, => Hij mag nog even uit

                ;Toon cursor op CSRX, CSRY

DISPCSR:        SET CSRON,(IY-FLAGS2)   ;Cursor nu AAN
                XOR A
                LD (BLKCNT),A           ;Knipperteller weer op 0
                BIT CSR,(IY+TABSAV)     ;Kleuren cursor?
                JR Z,DP5                ; Nee, => Toon chr(255)
INVCSR:         LD BC,(CSRY)            ;Wissel kleuren-cursor aan/uit
                CALL CLRADR             ;Haal adres & bitpos.
                JR Z,DP4                ; Bit 7? => DP4
DP3:            SRL B                   ; Nee, schuif [B] 1 pos naar rechts
                DEC A                   ;Verlaag teller
                JR NZ,DP3               ;Niet klaar? => Opnieuw
DP4:            LD A,C                  ;Haal colorbyte op
                XOR B                   ;Inverteer cursor
                JP NWRVRM               ;Schrijf nieuwe colorbyte
DP5:            LD A,2                  ;Toon 'oude' cursor
                LD (ESCCNT),A           ;VT-52 <ESC> 'y' 5
                LD A,'5'
                JP CHPUT                ;Zet cursor op het scherm

                ;Wis cursor op CSRX, CSRY

ERACSR:         LD A,(BLKOFF)           ;Haal de cursor UIT tijd
                OR A
                RET Z                   ; 0 => Altijd aan
                BIT KNIPPER,(IY+SAVFL2) ;Staat het knipperen aan?
                RET Z                   ; Nee, => AAN laten
DoEraCsr:       BIT CSRON,(IY-FLAGS2)   ;Is de csr al UIT?
                RET Z                   ; Ja, => Snel klaar
                RES CSRON,(IY-FLAGS2)   ;Vlag: Cursor = weg
                XOR A                   ;Cursorknippertijd teller op nul zetten
                LD (BLKCNT),A
                BIT CSR,(IY+TABSAV)     ;Kleuren cursor?
                JR NZ,INVCSR            ; Ja, => Wissel huidige colorbyte
                LD A,1                  ; Nee, wis de cursor
                LD (ESCCNT),A           ;VT-52 <ESC> 'x' 5
                LD A,'5'
                JP CHPUT

                ;Bereken adres in colortabel
                ;In: C=Ypos B=Xpos
                ;Uit: HL=Adres, C=VPEEK(HL), B=80H, A=Bitpositie in [C]

CLRADR:         LD A,B
                LD B,C
                LD DE,10                ;10 bytes per regel
                LD HL,-10               ;Begin bij -10
CA1:            ADD HL,DE               ;bereken regel begin
                DJNZ CA1
                DEC A
                LD C,A
                XOR A                   ;Wis carry
                SRL C                   ;Deel C door 8, rest in A
                RRA
                SRL C
                RRA
                SRL C
                RRA
                PUSH AF                 ;Bewaar rest
                LD D,0
                LD E,C
                ADD HL,DE               ;Tel xpos/8 bij vramadres op
                LD DE,(TXTCOL)
                ADD HL,DE               ;Tel colorbase erbij
                CALL NRDVRM             ;Haal colorbyte op in A
                LD C,A                  ;Bewaar gelezen byte
                POP AF
                LD B,5
CA2:            SRL A                   ;Maak doorschuif van rest af
                DJNZ CA2
                LD B,10000000B          ;Bit masker in B
                OR A                    ;Klaar?
                RET

                ;Kijk of de stop toets werd ingedrukt, zoja wissel cass. relais
                ; Handig bij overtikken van gedicteerde teksten

STOPKEY:        LD A,(INTFLG)           ;Haal STOP-toets vlag
                OR A                    ;Stop ingedrukt?
                RET Z                   ; Nee, => Klaar
                XOR A
                LD (INTFLG),A           ; Ja, wis hem weer
                DEC A                   ;Wissel het cassette motorrelais
                JP STMOTR


; ^Links, naar begin van regel
;
ctrlLeft:       res vir,(iy-flags6)     ;Geen virtuele cursor meer
                jp toRegStart           ;Naar positie 1

; ^Rechts, naar einde van regel
;
ctrlRight:      res vir,(iy-flags6)     ;Geen virtuele cursor meer
                jp toRegEnd             ;Naar regeleinde


                ;Verwerk ctrl/toetsdruk

control:        ld a,b                  ;Haal letter
                cp right                ;Rechts
                jr z,ctrlRight
                cp down                 ;Omlaag
                jp z,toets1
                cp up
                jp z,toets6             ;Omhoog
                cp left
                jr z,ctrlLeft           ;Links
                cp del
                jp z,removLn            ;Wis regel
                ld a,(newkey+8)
                rra
                rra                     ;Home ingedrukt?
                jp nc,cFormat           ; Ja, indelen vanaf cursor
                ld a,b                  ;Herstel teken in A
                ld hl,comln
                push hl                 ;Toon commandoregel
                call noCtrl             ;Maak hoofdletter
                ld b,a
                ld c,'^'
                ld a,' '
                push bc
                call cl0                ;Print ^X
                pop bc
                res twee,(iy-flags3)    ;Geen 2 tekens nodig
co1:            ld hl,crlTab
co2:            ld a,(hl)               ;Zoek in tabel
                inc hl
                cp b
                jr z,co3                ;Gevonden
                inc a
                ret z                   ;Klaar
co2b:           inc hl
                inc hl
                inc hl
                jr co2
CO3:            LD A,(HL)
                BIT TWEE,(IY-FLAGS3)    ;2e teken onderzoeken?
                JR Z,CO4                ; Nee, => CO4
                CP C                    ; Ja, test 2e teken
                JR Z,CO5                ;Gevonden
                JR CO2B                 ;Opnieuw
CO4:            OR A                    ;Nog een teken?
                JR Z,CO5                ; Nee, => Spring
                SET TWEE,(IY-FLAGS3)    ; Ja, Haal 2e teken
                LD A,(IY+XPOS)
                LD (CSRX),A
                LD A,(IY+YPOS)
                LD (CSRY),A
                CALL NCHGET
                CALL NOCTRL             ;Maak hoofdletter
                LD HL,3301H
                LD (CSRY),HL
                CALL NCHPUT             ;Print 2e teken
                CP '0'                  ;Cijfer?
                JR C,CO4B
                CP '9'+1
                JR NC,CO4B              ; Ja, zoek markering
                LD (IY-MRKNUM),A        ;Bewaar nummer
                LD A,'0'                ;Zoek '0'
CO4B:           LD C,A
                JR CO1                  ;Zoek 2e letter
CO5:            INC HL
                LD A,(HL)
                INC HL
                LD H,(HL)
                LD L,A
                JP (HL)                 ;Spring naar routine

                ;Wissel hoofd/kleine letter en ga naar rechts

chgCaseR:       call chgCase            ;Wissel huidige teken
ccr1:           call rechts             ;Cursor 1 pos. naar rechts
                ld a,(iy+xPos)          ;Bereken pos. van huidige kar.
                add a,(iy+offset)       ;Resulaat = 1-Based
                dec a                   ;0-Based maken
                ld hl,strBuf
                cp (hl)                 ;Voorbij regeleinde?
                jp nc,rechts            ; Ja, => Naar volgende regel
                inc l                   ;Skip het lengtebyte
                add a,l                 ;HL wordt pointer naar huidige kar.
                ld l,a                  ; H verandert niet, staat op 0c0h
                ld a,(hl)               ;Haal huidige kar.
                call cmpBlank           ;Is het een spatie karakter?
                jr z,ccr1               ; Ja, => Zoek verder naar volgende kar
                ret                     ; Nee, laat cursor staan

                ;Ga naar links en wissel hoofd/kleine letters

chgCaseL:       call links
                call chgCase            ;Wissel huidige teken
ccl1:           ld a,(iy+xPos)          ;Bereken pos. van huidige kar.
                add a,(iy+offset)       ;Resulaat = 1-Based
                dec a                   ;Begin van de regel?
                ret z                   ; Ja, => Blijf daar staan
                ld h,high strBuf        ;HL=String buffer
                ld l,a
                ld a,(hl)               ;Haal kar links van het huidige kar.
                call cmpBlank           ;Is het een spatie karakter?
                ret nz                  ; Nee, laat cursor staan
                call links              ; Ja, => Zoek verder naar volgende kar
                jr ccl1

                ;Wissel hoofd/kleine letter

chgCase:        ld a,(iy+xPos)          ;Bereken pos. van huidige kar.
                add a,(iy+offset)       ;Resulaat = 1-Based
                dec a                   ;0-Based maken
                ld hl,strBuf
                cp (hl)                 ;Voorbij regeleinde?
                ret nc                  ; Ja, => Klaar
                inc l                   ;Skip het lengtebyte
                add a,l                 ;HL wordt pointer naar huidige kar.
                ld l,a                  ; H verandert niet, staat op 0c0h
                ld a,(hl)               ;haal het karakter
                cp 'A'                  ;Is het een letter?
                ret c                   ; Nee, => Klaar
                cp 'Z'+1                ;Is het een hoofdletter?
                jr c,doChgCase          ; Ja, => Wordt kleine letter
                cp 'a'
                ret c
                cp 'z'+1                ;Kleine letter?
                ret nc                  ; Nee, => Klaar
doChgCase:      xor 00100000b           ;Wissel case-bit
                ld (hl),a               ;Bewaar het teken
                set change,(iy+flags1)  ;Zet "Regel gewijzigd" vlag
                ret

                ;Verwerk graph/toetsdruk

GRAPH:          LD A,B                  ;Haal letter
                CP LEFT                 ;Links
                JR Z,CHGCASEL           ; Ja, => Wissel boven/onderkast
                CP RIGHT                ;Rechts
                JR Z,CHGCASER           ; Ja, => Wissel boven/onderkast
                CP HOME                 ;Centreren?
                JP NZ,MAIN1             ; Nee, => Gewoon grafisch teken

CENTREER:       CALL TOREGSTART         ;Cursor naar positie 1
                LD HL,OMLAAG
                PUSH HL                 ;Straks ‚‚n regel omlaag
                LD HL,STRBUF
                LD A,(HL)               ;Haal regellengte
                OR A                    ;Nul?
                RET Z                   ; Ja, => Klaar
                LD B,A                  ;Verwijder alle voorloop spaties
CT1:            INC HL
                LD A,(HL)
                CP ' '                  ;Is teken een spatie?
                JR NZ,CT2               ; Nee, => Begin van regel gevonden
                DJNZ CT1                ; Ja, => Zoek verder
                RET
CT2:            SET CHANGE,(IY+FLAGS1)  ;Vlag: Regel is gewijzigd
                EX DE,HL
                LD HL,STRBUF
                PUSH HL
                LD (HL),B               ;Bewaar nieuwe regellengte
                INC HL
                EX DE,HL
                LD C,B
                LD B,0
                LDIR                    ;Wis alle spaties
                POP HL                  ;Herstel HL (Stringpointer)
                LD A,(IY+KLRECHTS)      ;Haal positie rechterkantlijn
                SUB (IY+KLLINKS)        ;Bereken regellengte
                SUB (HL)                ;Bereken aantal in te voegen spaties
                RET C                   ; <= 0, dan zijn we snel klaar-No Carry
                RRA                     ;Aantal spaties / 2 = Aantal invoegen
                ADD A,(IY+KLLINKS)      ;Regel opschuiven tot linkerkantlijn
                DEC A                   ;Kantlijn was 1-based, aanpassen
                RET Z                   ;Nul spaties invoegen => Klaar
                LD D,0
                LD E,A                  ;DE = Aantal spaties links invoegen
                LD B,D
                LD C,(HL)               ;BC=Lengte van regel
                ADD A,C                 ;Wordt de regel lang dan 254 tekens?
                RET C
                CP 254
                RET NC                  ; Ja, => Stoppen
                LD (HL),A               ; Nee, bewaar nieuwe regellengte
                ADD HL,BC
                PUSH HL                 ;HL=Adres laatste teken in regel
                LD A,E                  ; A=Aantal in te voegen spaties
                ADD HL,DE
                EX DE,HL                ;DE=Bestemmingsadres
                POP HL
                LDDR                    ;Schuif regel op
                LD B,A                  ;B=Aantal ingevoegde spaties
                PUSH BC
                XOR A
                SCF
                CALL BLKPS3             ;Evt. BLOKpos aanpassen
                POP BC
                LD HL,STRBUF+1
CT3:            LD (HL),' '             ;Voor kantlijn schoonmaken met spaties
                INC HL                  ; met spaties
                DJNZ CT3
                RET

                ;Diverse foutmeldingen

NOTFOUND:       LD HL,TNOTFND
                CALL MESKEY             ;Niet gevonden
                LD HL,(CSRNUM)
                JP GOTOLINE

                ;Geheugen vol

MEMVOL:         LD HL,TMEMVOL
                CALL MESKEY
                LD HL,(CSRNUM)
                PUSH HL
                CALL GOTOLINE           ;Wis deze regel
                POP HL
                LD DE,(LASTLINE)
                OR A
                SBC HL,DE               ;Cursor op/voorbij laatste regel?
                DEC DE                  ; dus is de pointerruite op?
                EX DE,HL
                CALL NC,GOTOLINE        ;  Ja, ga een regel omhoog
                JR ERROR

; fullPageTab
;
; Toon foutmelding en keer terug naar hoofdlus
;
fullPageTab:    ld hl,tPageTabFull      ;Pagina tabel vol
                jr errToCurLine         ;Toon fout + Naar huidige regel


                ;Regel te lang

REGLANG:        CALL EVTOPSLAAN
                LD HL,TREGLEN
errToCurLine:   CALL MESKEY
REGL2:          LD HL,(CSRNUM)
                CALL GOTOLINE
                JR ERROR

                ;Record einde niet gevonden

RECERR:         LD HL,TRECERR
                JR ErrToCurLine

                ;Onderbroken

ONDERBR:        LD HL,TONDERB
                JR ErrToCurLine

                ;Verkeerde TED versie

VERSERR:        CALL CLOSEBF
                LD HL,TVERERR
                JP MESKEY

                ;Karakterset niet gevonden

KARERR:         CALL CLOSEBF
                LD HL,TKARERR
                JP MESKEY

                ;Disk vol

diskVol:        ld hl,tDiskvol
                call mesKey

                ;Ga verder na systeem fout

error:          bit ldFl,(iy+flags1)    ;Load error?
                call nz,lo15            ; Ja, => Sluit bestanden + Geheugen
                call closeBf            ;Sluit bestanden
                call chkPageTab         ;Check op illegale paginastops
                res dispOff,(iy-flags5) ;Scherm opbouw activeren
                xor a
                ld (fKeyNum),a          ;Geen funktietoets
                call comLn              ;Standaard commandoregel tonen
                res insFl,(iy+flags1)
                call insert             ;Insert aan
                res blokFl,(iy+flags1)  ;Wis bloklaad vlag
                res vir,(iy-flags6)     ;Geen virtuele cursor meer
                jp main                 ;Naar hoofdlus

                ;Meld fatale diskette fout

DSKERR:         PUSH IY
                PUSH IX
                LD HL,(CSRY)
                PUSH HL                 ;Bewaar cursor pos.
                LD IY,TABEL             ;IY is gewist door DOS
                LD A,C                  ;Haal errornummer
                AND 11111110B           ; Wis read/write vlag
                LD HL,TPROT
                JR Z,DSE1               ;=> Write protected
                CP 010B
                LD HL,TNODISK
                JR Z,DSE1               ;=> Geen diskette
                LD HL,TDSKERR           ;=> Disk error
DSE1:           SET ERR,(IY-FLAGS5)     ;Zet error vlag (geen DOS calls)
                CALL MESSAGE            ;*** Foutmelding ***
                LD DE,TPROB
                CALL STROUT             ;Opnieuw proberen? (j/n)
DSE2:           CALL INKCRL             ;Wacht op (ctrl) toets
                CP 'J'
                JR NZ,DSE3
                LD HL,TMOMENT
                CALL MESSAGE            ;Momentje...
                RES ERR,(IY-FLAGS5)
                LD C,1
                POP HL
                LD (CSRY),HL
                POP IX
                POP IY
                RET                     ;Retry
DSE3:           CP 'N'
                JR NZ,DSE2
DSE4:           LD SP,STACK             ;Herstel stack pointer
                RES ERR,(IY-FLAGS5)
                LD HL,(CSRNUM)
                CALL GOTOLINE
                JP ERROR                ;Abort => Terug

                ;Naar Check again

CHECKAG:        LD DE,CHECK2-987H
                JP CDE1

                ;Interrupt afhandeling klokje en lichtkrant

INT:            BIT ERR,(IY-FLAGS5)     ;Aangeroepen door error routine?
                RET NZ                  ; Ja, => Terug dos 1 geeft stackproblem
                LD HL,(INTCNT)          ;Haal teller
                LD DE,-15
                OR A
                SBC HL,DE               ;Meer dan 15 * 0.02 sec verstreken?
                RET NC                  ; Nee, => Klaar
                LD HL,-1
                LD (INTCNT),HL          ;Interruptteller weer op 1 tel
                LD C,GETTIME
                CALL DOS                ;Haal tijd
                PUSH DE                 ;Bewaar seconden
                PUSH HL                 ;Bewaar uren/minuten
                LD HL,55                ;Locate 0,55
                CALL NSTWRT
                BIT KRT,(IY-FLAGS3)     ;Lichtkrant aan?
                JR NZ,INT0              ; Ja, schuif op
                LD HL,TNOKRT
                JR INT2                 ;Geen lichtkrant
INT0:           LD HL,(KRTPOS)          ;Haal lichtkrant begin
                INC HL                  ; 1 teken verder
                LD (KRTPOS),HL
                LD DE,KRTEND
                OR A
                SBC HL,DE               ;Aan het einde van krant?
                JR C,INT1               ; Nee, Ok
                LD HL,KRTSTART          ; Ja, naar begin
                LD (KRTPOS),HL
INT1:           LD HL,(KRTPOS)          ;Haal bron
INT2:           LD B,15                 ;Print 15 tekens
                LD C,(IY+VDPWRITE)      ;C=VDP poort, 98H
                OTIR                    ;Print de lichtkrant
                EX (SP),HL              ;Pauze
                EX (SP),HL
                LD A,']'                ;'] '
                OUT (C),A
                EX (SP),HL
                EX (SP),HL
                LD A,' '
                OUT (C),A
                POP HL
                PUSH HL
                RES VRLOOP,(IY-FLAGS3)  ;Geen voorloopnullen
                LD A,H
                CALL PRTKLK             ;Print uren
                LD A,'.'
                OUT (C),A
                POP HL
                BIT VOORNUL,(IY+SAVFL)  ;Voorloopnullen gekozen?
                JR Z,INT3
                SET VRLOOP,(IY-FLAGS3)  ; Ja, zet tijdelijke vlag
INT3:           LD A,L
                CALL PRTKLK             ;Print minuten
                LD A,':'
                OUT (C),A
                POP DE
                LD A,D
                JP PRTKLK               ;Print seconden

                ;Print binairgetal als BCD

BCDSET:         CALL SETVDP             ;Zet vdp klaar
PRTBCD:         SCF                     ;C => Spatie aan einde
                RES VRLOOP,(IY-FLAGS3)  ;Geen voorloop nullen
                JR PRB0
PRTKLK:         OR A                    ;Geen spatie aan einde
PRB0:           PUSH AF
                LD A,(IY+VDPWRITE)
                LD C,A
                POP AF
                PUSH AF
                LD B,255                ;B=Honderdtallen
PRB1:           INC B
                SUB 100
                JR NC,PRB1
                ADD A,100
                LD L,255
PRB2:           INC L                   ;Print tientallen
                SUB 10
                JR NC,PRB2
                ADD A,10
                LD H,A
                LD A,B
                OR A
                JR Z,PRB3
                ADD A,'0'
                OUT (C),A
                LD A,L
                JR PRB4
PRB3:           LD A,L
                OR A                    ;>10?
                JR NZ,PRB4              ; Ja, => Druk tientallen af
                LD A,' '
                BIT VRLOOP,(IY-FLAGS3)  ;Voorloopnul printen?
                JR Z,PRB5               ; Nee, => spatie
                XOR A
PRB4:           ADD A,'0'
PRB5:           OUT (C),A
                LD A,H                  ;Print eenheden
                ADD A,'0'
                OUT (C),A
                POP AF                  ;Haal spatievlag
                RET NC                  ;NC => Geen spatie
                LD A,' '
                OUT (C),A
                RET

                ;Vul karakterpatroon in in videoram

MAKEKAR:        LD B,8
MK1:            LD A,(DE)
                CALL NWRVRM
                INC DE
                INC HL
                DJNZ MK1
                RET

                ;Spring naar GETCODE

TOCODE:         LD DE,GETCODE-987H
                JR CDE1

TOACCESS:
if              not (DEMO or AUTODEMO)  ;Voorkom undefined global
                LD DE,ACCESS-987H       ;  in DEMO versie
                JR CDE1
endif

TOCHECK:
if              not (DEMO or AUTODEMO)
                LD DE,CHECK-987H
                JR CDE1
endif

                ;Codeer routine

CODE:           LD DE,DECODE-987H
CDE1:           LD HL,(ADDCODE)
                EX (SP),HL              ;=JP decode
                EX (SP),HL
                ADD HL,DE
                PUSH HL
                RET


                ;Zoek memory-mapper

zoekMap:        bit  mMan,(iy-flags5)
                ret  nz                 ;Alleen onder dos1 meer keren ramzoeken
                bit  d2mm,(iy-flags4)   ; toegestaan, om het MM gebruik voor
                ret  nz                 ; de ramdisk UIT te kunnen zetten

                ld   (iy-pg1Seg),-1     ;Page 1 niet gebruiken indien pseg

                ld   de,memMan+iniChk   ;Device 4D (MemMan) Func. 30 (IniChk)
                ld   a,1-'M'
                call extBios            ;Roep MemMan aan
                dec  a                  ;Is A verhoogd met 'M'?
                jr   nz,zmDos2          ; Nee, => Geen MemMan gevonden
                cp   d                  ;Is het versie nummer minstens 1.1?
                jp   z,mManErr          ; Nee, => Verkeerde memMan versie
                dec  d                  ;Versie hoger 1.xx?
                jr   nz,mManOk          ; Ja, => Prima
                cp   e                  ;Versie 1.0?
                jp   z,mManErr          ; Ja, => Error

mmanOk:         set  mman,(iy-flags5)   ; Ja, zet vlag: MemMan aanwezig
                ld   de,memMan+Info
                ld   b,2
                call extBios            ;Haal FastUse jump-adres
                ld   (mmUse2+1),hl      ;Zet JumP naar het MemMan.Use adres

                ld   b,1                ;Haal current Page1 segment
                ld   de,memMan+GetCur
                call extBios            ;Haal huidige segment in page 1
                ld   de,mmTabel
                ld   b,7                ;Alleen 8 vram pagina's gevonden (0..7)
                inc  a                  ;Is het een FSEG?
                jr   nz,noFseg          ; Nee, => Onbruikbaar voor page 2
                ld   (mmTabel),hl       ; Ja, zet het als eerste entry in
                inc  de                 ;  de tabel
                inc  de
                inc  b                  ;Aantal seg's is nu 8
                ld   (iy-pg1seg),b      ;Segment in pag1 nu doet ook mee, nr. 8
noFseg:         push de
                push bc
                ld   b,2
                ld   de,memMan+GetCur
                call extBios            ;Haal huidige segment in page 2
                pop  bc
                pop  de
                inc  b                  ;Weer een segment erbij
                ex   de,hl
                ld   (hl),e             ;Zet de ID pointer in de tabel
                inc  hl
                ld   (hl),d
                inc  hl
                ex   de,hl              ;[DE] = 1e vrije entry in mmTabel

                LD   C,maxMapSeg+8-1    ;C=Max aant. segmenten+VRAM; 0-based
MEMALOC:        PUSH DE                 ;Bewaar positie in segmenttabel
                PUSH BC                 ;Bewaar huidige segment teller
                LD   B,2                ;Allocate segment exclusief in pagina 2
                LD   DE,memMan+Alloc
                CALL EXTBIOS
                POP  BC
                POP  DE
                LD   A,H
                OR   L                  ;Segment nummer = 0?
                JR   Z,MEMDONE          ; Ja, => geen vrije segmenten (meer)
                EX   DE,HL
                LD   (HL),E             ;Bewaar segment code
                INC  HL
                LD   (HL),D
                INC  HL
                EX   DE,HL
                INC  B                  ;Verhoog segmentteller
                LD   A,B
                CP   C                  ;Maximum bereikt?
                JR   NZ,MEMALOC         ; Nee, => Volgende segment
MEMDONE:        LD   (IY+MAXMAP),B      ; Ja, Vul aantal segmenten in
                RET

ZMDOS2:         XOR A
                LD DE,0402H             ;Device 4 (Mapper control) Func. 2
                CALL EXTBIOS            ;Roep DOS2 aan
                OR A                    ;Mapper routines aanwezig?
                JR Z,ZMDOS1             ; Nee, => DOS1
                LD (ALLSEG+1),HL        ; Ja, vul jumptabel in
                INC HL
                INC HL
                INC HL
                LD (FRESEG+1),HL        ;Free segment routine
                LD DE,21H-3
                ADD HL,DE
                LD (GETP1+1),HL         ;Get page 1 segment
                LD DE,3
                ADD HL,DE
                LD (PUTP2+1),HL         ;Put page 2 segment
                ADD HL,DE
                LD (GETP2+1),HL         ;Get page 2 segment

                SET D2MM,(IY-FLAGS4)    ;Vlag: DOS2 mapper device aanwezig
                LD (IY-PG1SEG),8        ;Segment van page 1 = nr. 8

                LD HL,MMTABEL           ;[HL] nummers beschikbare segmenten
                CALL GETP1
                LD (HL),B               ;Primary Mapper slot adres
                INC HL
                LD (HL),A               ;Huidig pagina-1 segment
                INC HL
                CALL GETP2
                LD (HL),B               ;Primary Mapper slot adres
                INC HL
                LD (HL),A               ;Huidig pagina-2 segment
                INC HL
                LD E,9                  ;E=Huidig seg (0-7=Vram, 8-9=Mapper),
ZM1:            LD A,B                  ; Max 127 segmenten
                AND 10001111B
                SET 5,A                 ;Selecteer segment in willekeurig slot
                LD B,A
                XOR A                   ;Allocate user segment
                CALL ALLSEG
                JR C,ZM2                ;Geen vrije segmenten
                LD (HL),B               ;Bewaar slot adres
                INC HL
                LD (HL),A               ;Bewaar segment nummer
                INC HL
                INC E
                LD A,maxMapSeg+8-1      ;128 mapper + Vram segmenten?
                CP E
                JR NZ,ZM1               ; Nee, => Volgende segment
ZM2:            LD (IY+MAXMAP),E        ; Ja, klaar, vul aantal segmenten in
                RET

zmDos1:         ld hl,08000h            ;Zoek mapper onder DOS1
                ld a,(savFD)
                out (0feh),a            ;Kijk of er een MM is
                ld e,(hl)               ;Bewaar byte (is in TED pagina!)
                ld (hl),0
                ld a,(savFE)
                out (0feh),a
                ld (hl),0ffh
                ld a,(savFD)
                out (0feh),a
                ld a,0ffh
                cp (hl)
                ld (hl),e               ;Herstel byte
                ld a,8                  ;0-7 is VRAM, 8 is 1 pagina RAM
                jr z,mm4                ;Geen memory mapper => MM4
                inc a                   ;Wel mapper, 7 pages VRAM en 2 Pages MM
                bit 0,(iy+mapFlag)      ; MM vrijhouden voor Ramdisk?
                jr nz,mm3               ;  Ja, => alleen map 1 en 2 gebruiken
                call findPbTed          ;PB.COM geinstalleerd?
                bit pbTed,(iy-flags6)   ;Resultaat testen
                ld a,9
                jr nz,mm3               ; Ja, => Gebruik geen MM

                ld hl,seg0identifier    ;Zet herkenning neer in page 3
                ld de,0c000h            ;Begin van mapper segment 0
                ld bc,identLen          ;Zoveel bytes
                ldir                    ;Verplaatsen naar page 3

                ld c,4                  ;Begin op mapperblok 4; min. mapper=64k
mmGetMapSizeLp: ld a,c                  ;Haal huidige blok
                out (0feh),a            ;Schakel blok in op 8000h
                ld hl,seg0identifier    ;Kijk of mapper segment 0
                ld de,08000h            ; is aangeschakeld
                ld b,identLen           ;Vergelijk zoveel bytes
mmCmpIdentLp:   ld a,(de)
                cp (hl)                 ;Identifier in dit blok?
                jr nz,mmNoSeg0          ; Nee, => Niet mapper blok 0
                inc hl
                inc de
                djnz mmCmpIdentLp
                jr mmLastSegFound       ; Ja, => Segment 0 is weer bereikt
mmNoSeg0:       ld hl,8000h             ;Test of er RAM in het segment zit
                ld (hl),l               ;Zet 0 op 8000h
                ld a,(hl)
                cp l                    ;0 bewaard?
                jr nz,mmLastSegFound    ; Nee, => Einde van mapper bereikt
                ld (hl),h               ;Zet 80h op 8000h
                ld a,(hl)
                cp h                    ;80h bewaard?
                jr nz,mmLastSegFound    ; Nee, => Einde van mapper bereikt
                inc c                   ;Naar volgende segment
                ld a,c                  ;Haal dat segment, kijk of het nog past
                cp maxMapSeg+2+1        ;Tel page 0 en 3 niet mee; voorbij end?
                jr nz,mmGetMapSizeLp    ; Ja, => Onderzoek het segment
mmLastSegFound: ld a,c                  ;Haal huidige segment nr.
                add a,5                 ;-1=0 based; -2=pag 0&3; +8=VRAM
mm3:            ld (iy-pg1Seg),9        ;Mapper segment van pag1 = blok 2
mm4:            ld (iy+maxMap),a        ;Bewaar hoogste segmentnummer
                ret

seg0identifier: 'MJV DOS1 Mapper Search';Segment 0 identifier
identLen        equ $-seg0identifier    ;Identifier length


; findPB
;
; Kijk of printerbuffer aanwezig is
;
findPb:         bit mMan,(iy-flags5)    ;MemMan aanwezig?
                jr z,findPbTed          ; Nee, => Dus ook geen TSR's

                ld hl,tPbID             ;TSR ID-Name in HL
                ld de,memMan+getTsrID   ;MemMan functie: Vraag TSR ID
                call extBios            ;Roep memman aan
                jr c,findPbTed          ; => PB.TSR niet gevonden
                ld (pbTsrID),bc         ;Bewaar TSR ID-code
                set pbTsr,(iy-flags6)   ;PB.TSR gevonden

findPbTed:      ld a,(h.lptO)           ;Zoek PB.COM
                cp 0c9h                 ;Is de TED printerbuffer aanwezig?
                ret z                   ; Nee, => Geen PB
                ld hl,(pbID)            ;Haal ID-bytes
                ld bc,'BP'
                or a
                sbc hl,bc
                ret nz
                set pbTed,(iy-flags6)   ;PB.COM gevonden
                ret

tPbID:          db 'MJV Printbuf'       ;ID-Naam van de printbuffer TSR


                ;Haal filenaam en vul in in FCB1 (DOS 005CH)

NAAM:           CALL GETFLEN            ;Haal max. naam lengte in B
                LD E,1                  ;Alleen hoofdletters
                CALL GETTXT             ;Voer naam in
NAAM2:          BIT DOS2,(IY-FLAGS5)
                JR Z,NAAM3              ;DOS1 => Maak FCB
                LD C,(HL)               ;Haal lengte byte op
                LD A,C                  ;DOS2, path/filename naar BUF
                OR A
                SCF
                RET Z                   ;Terug indien lengte=0
                LD (BUF),A              ;Vul stringlengte in BUF in
                INC HL
                LD B,0
                LD DE,BUF+1             ;String naar buf+1 (als hij daar al
                LDIR                    ; niet stond)
                XOR A
                LD (DE),A               ;Nul als afsluiting
                LD DE,BUF+1             ;Pathname in DE
                LD BC,PARSE             ;Parse pathname
                CALL DOS
                XOR A
                LD (DE),A               ;Nul als afsluiting
                EX DE,HL
                LD DE,BUF+1
                PUSH HL                 ;Bewaar eindadres van naam
                OR A
                SBC HL,DE               ;Bereken nieuwe lengte
                EX DE,HL
                DEC HL
                LD (HL),E               ;Vul nieuwe lengte in BUF in
                POP DE                  ;Herstel eindadres in DE
                SCF
                RET Z                   ;Terug indien lengte=0
                BIT 0,B                 ;Alleen drivenaam opgegeven?
                RET Z                   ; Ja, => Error
                BIT 3,B                 ;Filenaam?
                JR NZ,NM1               ; Ja, => Ok
                BIT 1,B                 ;Pathname?
                RET Z                   ; Nee, => Error
                OR A                    ; Ja, klaar
                RET
NM1:            OR A
                BIT 4,B                 ;Extensie?
                RET NZ                  ; Ja, => Ok.
                LD A,(BUF)              ; Nee, vul standaard extensie in
                CP 63-4
                RET NC                  ;Terug indien string > 63 tekens
                ADD A,4
                LD (BUF),A              ;4 karakters erbij
                LD A,'.'
                LD (DE),A
                INC DE
                LD HL,TEXTENS           ;Vul standaard extensie in
                LD BC,3
                LDIR
                XOR A
                LD (DE),A               ;En vul nul in
                LD HL,BUF
                JR NAAM2                ;En kijk of extensie o.k. is

NAAM3:          LD HL,FCB1
                LD (HL),0               ;Default drive
                LD DE,FCB1+1
                LD BC,31
                LDIR
                LD HL,FCB1+1
                LD (HL),' '
                LD DE,FCB1+2
                LD BC,10
                LDIR
                LD A,(BUF)
                LD C,A                  ;C=Buflengte
                OR A
                SCF
                RET Z
                LD HL,BUF+1
                CP 1                    ;Naamlengte=1?
                JR Z,NAM1               ; => Geen drive aangegeven
                INC HL                  ;Onderzoek drive nummer
                LD A,(HL)
                DEC HL
                CP ':'
                JR NZ,NAM1
                LD A,(HL)
                INC HL
                INC HL
                SUB 'A'-1
                CP 9
                CCF
                RET C                   ;Bad drive name
                LD (FCB1),A             ;Vul drive nummer in
                DEC C
                DEC C                   ;Alleen drive opgegeven?
                JR NZ,NAM1
                INC C
                LD (HL),'*'             ; Ja, => A:*.txt
NAM1:           LD DE,FCB1+1
                LD B,8
NAM2:           LD A,(HL)               ;Lees naam in
                CP '.'
                JR Z,NAM4
                CP '*'
                CALL Z,STER             ;Vervang '*' in '?'
                LD A,B                  ;Acht tekens gehad?
                OR A
                JR Z,NAM3               ; Ja, => Zoek naar '.'
                LD A,(HL)
                LD (DE),A
                INC DE
                DEC B
NAM3:           DEC C
                JR Z,MAKETXT            ;Geen '.' => Standaard .TXT
                INC HL
                JR NAM2
NAM4:           LD DE,FCB1+9            ;Lees extensie in
                LD B,3
                JR NAM6
NAM5:           LD A,(HL)
                CP '*'
                CALL Z,STER
                LD A,B
                OR A
                JR Z,NAM6
                LD A,(HL)
                LD (DE),A
                INC DE
                DEC B
NAM6:           OR A                    ;Wis carry
                DEC C
                RET Z
                INC HL
                JR NAM5
MAKETXT:        LD DE,FCB1+9            ;Maak extensie .TXT (voorkeursext.)
                LD HL,TEXTENS
                LD BC,3
                LDIR
                OR A
                RET
STER:           LD A,B
                OR A
                RET Z
                LD A,'?'                ;Vul naam in met '?'ens
                LD (DE),A
                DEC B
                INC DE
                JR STER

                ;Bewaar FCB in SAVNAM

SAVFCB:         LD DE,SAVNAM            ;Bewaar naam voor saven
SFCB2:          BIT DOS2,(IY-FLAGS5)
                JR Z,SVN0               ;=> Haal DOS1 FCB
                LD HL,BUF
                LD B,0
                LD C,(HL)
                INC C                   ;Lengtebyte en afsluitnul ook meenemen
                INC C
                LDIR                    ;Copieer DOS2 path/filename
                JP PRTSAV
SVN0:           PUSH DE
                INC DE                  ;Lengtebyte overslaan
                LD HL,FCB1
                LD BC,0
                LD A,(HL)               ;Haal drive-letter
                INC HL
                OR A
                JR Z,SVN1               ;Default drive=niets
                ADD A,'A'-1
                LD (DE),A
                INC DE
                INC C
                LD A,':'                ;Vul drive in
                LD (DE),A
                INC DE
                INC C
SVN1:           LD A,(HL)
                CP ' '                  ;Naam klaar?
                JR Z,SVN2               ; Ja, => Extensie
                LD (DE),A
                INC B
                INC HL
                INC DE
                LD A,B
                CP 8
                JR C,SVN1
SVN2:           LD A,'.'                ;Vul extensie in
                LD (DE),A
                INC DE
                INC B
                LD HL,FCB1+9
                LD A,B
                ADD A,C
                LD C,A                  ;Bewaar lengte
                LD B,0
SVN3:           LD A,(HL)
                CP ' '                  ;Extensie klaar?
                JR Z,SVN4               ; Ja, => Ok
                LD (DE),A
                INC B
                INC HL
                INC DE
                LD A,B
                CP 3
                JR C,SVN3
SVN4:           LD A,B
                ADD A,C
                POP HL
                LD (HL),A               ;Vul lengtebyte in
                JP PRTSAV

                ;Bepaal maximale file/path lengte

GETFLEN:        LD B,14
                BIT DOS2,(IY-FLAGS5)
                RET Z                   ;DOS1 max 14 kars
                LD B,63                 ;DOS2 max 63 kars
                RET

if              DEMO or AUTODEMO        ;Demo versie van TED?

SAVEBLOK:
SAVE:
SAVE1:
SV0B:           LD HL,TDEMO             ; Ja, Tekst: Demoversie - Bewaren
                JP MESKEY

TDEMO:          db TAB,'*** Demoversie - Bewaren niet mogelijk',NUL

else                                    ; Nee, assembleer de bewaar funtie wel

                ;Bewaar huidige blok

SAVEBLOK:       CALL EVTOPSLAAN
                LD HL,(BSTARTLN)
                LD DE,(BENDLN)
                CALL DCOMPR             ;Is blok aanwezig?
                JR C,SB1
                RET NZ                  ; Nee, => Terug
                LD A,(IY-BSRTPOS)
                SUB (IY-BENDPOS)
                RET NC
SB1:            LD (SAVESTART),HL       ;Startregel
                LD (SAVEEND),DE         ;Laatste regel
                SET BLOKFL,(IY+FLAGS1)  ;Geef bloksave aan
                CALL SAVE1              ;Save blok
                RES BLOKFL,(IY+FLAGS1)
                RET

                ;Bewaar huidige tekst

SAVE:           CALL EVTOPSLAAN         ;Bewaar huidige regel
                LD HL,0
                LD (SAVESTART),HL       ;Beginnen bij regel 0
                LD HL,(LASTLINE)        ;Haal laatste regelnummer in HL
                LD A,H
                OR L                    ;Nul regels in Mem?
                JR Z,SV0
                DEC HL                  ; Nee, laatste regel hoeft niet (altijd leeg)
SV0:            LD (SAVEEND),HL

SAVE1:          LD HL,TSAVNAM           ;Entry voor saveblok
                BIT DOS2,(IY-FLAGS5)    ;DOS2 pathname?
                JR Z,SV0A
                INC HL                  ; Ja, sla de 3 tabs over
                INC HL
                INC HL
SV0A:           LD C,1
                CALL INVOER             ;Haal Save-naam
                BIT BLOKFL,(IY+FLAGS1)  ;Blok saven?
                JR NZ,SV0C              ; Ja, => Geen oude naam
                LD HL,SAVNAM            ; Nee, toon load-naam
                LD E,1
                CALL GETFLEN            ;Haal max. file/path lengte in B
                CALL GETOLD             ;Voer naam in
SV0B:           CALL NAAM2              ;Haal naam
                RET C
                BIT SVINS,(IY+SAVFL2)   ;Instellingen ook bewaren?
                CALL NZ,SAVINSE         ; Ja, bewaar instellingen
                JR SAVE2                ;Bewaar de tekst
SV0C:           CALL NAAM
SV0D:           RET C
save2:          ld hl,tMoment
                call message            ;Momentje...
                ld a,create
                call maakFCB
                ret c
                call disVdpInt          ;VDP interrupts uitschakelen (sneller)
                bit blokFl,(iy+flags1)  ;Blok saven?
                call z,savFCB           ; Nee, => Bewaar nieuwe naam
                xor a
                ld (iy+endSav),a
                ld (iy+bufLen),a
                ld hl,diskBuf
                ld (bufPoint),hl        ;Lege buffer
                ld de,diskBuf
                ld c,setDMA             ;Zet DMA adres
                call dos
                ld de,(saveStart)       ;DE=Beginregel
                ld hl,(saveEnd)         ;HL=Laatste regel

sv1:            push hl
                push de
                res tabFl,(iy+flags1)   ;Geen ' of " geweest
                ld hl,strBf2            ;Haal regel in STRBF2
                bit stoTab,(iy+tabSav)  ;TABs op disk?
                jr z,sv2                ; Nee, => haal string zonder tabs
                call get2               ; Ja, laat tabs (chr 255) zitten
                jr sv2b
sv2:            call get                ;Haal string zonder TAB-tekens
sv2b:           or a
                jp z,sv9                ;Lengte=0 => Vul return in
                bit blokFl,(iy+flags1)  ;Blok bewaren?
                jp z,sv2e               ; Nee, => jump snel verder
                pop de                  ; Ja, haal huidige en laatste regel
                pop hl
                push hl
                push de
                sbc hl,de               ;Is dit de laatste regel?
                jr nz,sv2c              ; Nee, => Kijk of het de 1e is
                ld hl,strBf2            ; Ja, haal regel in STRBF2
                call get                ;  zonder spaties
                ld a,(iy-bEndPos)
                ld (hl),a               ;Kort regel in tot einde van het blok
                or a                    ;Blokeinde op pos. 0?
                jp z,sv9                ; Ja, => Regel is klaar
                pop de
                push de                 ;Herstel regelnummer
                ld hl,(saveStart)
                or a
                sbc hl,de               ;Is dit de 1e regel?
                jr nz,sv2e              ; Nee, => Klaar
                jr sv2d                 ; Ja, => Blokeinde en -begin in dezelfde regel
sv2c:           ld hl,(saveStart)
                or a
                sbc hl,de               ;Is dit de 1e regel?
                jr nz,sv2e              ; Nee, => Klaar
                ld hl,strBf2            ; Ja, haal regel in STRBF2
                call get                ;  zonder spaties
sv2d:           ld hl,strBf2            ;HL=Stringbuffer
                ld a,(hl)
                ld b,0
                ld c,(iy-bSrtPos)
                add hl,bc               ;Ga naar start van blok
                sub c
                jp z,sv9                ;Lege regel => Klaar
                jp c,sv9                ; Hoort niet voor te kunnen komen
                ld (strBf2),a           ;Geef nieuwe lengte aan
                inc hl                  ;Geen lengtebyte
                jr sv2f

sv2e:           ld hl,strBf2+1          ;String staat in string buffer 2
sv2f:           xor a
                ld (iy-spaties),a       ;Spatie teller=0
                ld c,a                  ;C=positie in bronregel

sv3:            ld a,(hl)
                cp ' '                  ;Spatie?
                jp nz,sv4               ; Nee, => Gewoon verplaatsen
                bit stoTab,(iy+tabSav)  ;Naar TABs omvormen?
                jr z,sv3b               ; Nee, => Gewoon spaties
                BIT TABFL,(IY+FLAGS1)   ;Onderdeel v/e string tussen "?
                JR NZ,SV3B              ; Ja, => Vul spaties in
                BIT STTAB,(IY+TABSAV)   ;Staan TABs al in string?
                JR NZ,SV3B              ; Ja, => Dat schiet lekker op
                INC (IY-SPATIES)        ;1 spatie meer
                PUSH HL
                LD E,A                  ;Bewaar teken
                LD B,0
                LD HL,TTAB+1
                ADD HL,BC               ;Bereken pos in TAB regel
                LD A,(HL)
                OR A                    ;Is er een TAB-stop?
                LD A,E
                POP HL
                JR Z,SV8                ; Nee, => Volgende teken
                LD A,(IY-SPATIES)
                LD (IY-SPATIES),0
                DEC A                   ; Slechts 1 spatie geweest?
                LD A,' '
                JR Z,SV4                ; Ja, => Vul spatie in
                LD A,TAB                ; Nee, => Vul Tab in
SV3B:           EX DE,HL
                LD HL,(BUFPOINT)
                JR SV7B                 ;Vul het teken direkt in
SV4:            EX DE,HL                ;Bewaar bron in DE
                LD B,A                  ;Bewaar teken
                LD A,(IY-SPATIES)       ;Waren er spaties geweest?
                OR A
                JR Z,SV6                ; Nee, => Vul teken in
                LD HL,(BUFPOINT)
SV5:            LD (HL),' '             ; Ja, eerst spaties invullen
                INC HL
                DEC A
                JR NZ,SV5
                LD (IY-SPATIES),0
                JR SV7                  ;Vul daarna teken in
SV6:            LD HL,(BUFPOINT)
SV7:            LD A,B
                CP 127                  ;Control-teken?
                JP NZ,SV7A              ; Nee, => Gewoon grafisch
                INC DE                  ; Ja, haal volgende teken
                INC C
                LD A,(STRBF2)
                CP C                    ;Alles gehad?
                JR Z,SV9                ; Ja, => Regel klaar
                LD A,(DE)               ;Haal teken op
                SUB 'A'-1               ;^A wordt ascii 1
                JR SV7B                 ;Vul in in diskbuffer
SV7A:           CP ' '                  ;Grafisch teken?
                JP NC,SV7AB             ; Nee, => Ok
                OR A                    ;       ESCape teken? (Ascii 0)
                LD A,ESC
                JR Z,SV7B               ;        Ja, => Vul ESC in.
                LD A,1                  ; Ja, maak CHR$(1)+Teken
                LD (HL),A
                INC HL
                LD A,B                  ;Vul grafische teken in
                ADD A,'A'-1
                JR SV7B
SV7AB:          CP 255                  ;Intern TAB teken?
                JP NZ,SV7B              ; Nee, => SV7B
                LD A,TAB                ; Ja, vul TAB (Ascii 9) in
SV7B:           LD (HL),A               ;Sla teken op in buffer
                INC HL
                LD (BUFPOINT),HL
                EX DE,HL
                CP "'"                  ;Was teken een ' ?
                JR Z,SV7C               ; Ja, => TABs niet gebruiken
                CP '"'
                JP NZ,SV8
SV7C:           SET TABFL,(IY+FLAGS1)   ;In een string geen TABs
SV8:            INC C                   ;Verhoog bron teller
                INC HL
                LD A,(STRBF2)
                CP C                    ;Alles gehad?
                JP NZ,SV3               ; Nee, => Volgende teken
                LD A,(IY-SPATIES)       ;Laatste tekens spaties?
                OR A
                JR Z,SV9                ; Nee, => Vul return in
                LD HL,(BUFPOINT)
                LD (HL),' '             ; Ja, vul spatie in
                INC HL
                JR SV10

SV9:            LD HL,(BUFPOINT)
SV10:           LD (HL),CR              ;Vul return in
                INC HL
                LD (HL),LF
                INC HL
                LD (BUFPOINT),HL
                LD DE,(ENDTPA)
                DEC D                   ;SUB DE,512  grafische tekens zijn 2
                DEC D                   ; bytes, dus raakt de buffer eerder vol
                OR A
                SBC HL,DE
                CALL NC,SAVEBUF         ;Vol => leeg buffer
                POP DE
                POP HL
                CALL DCOMPR             ;Alle regels gehad?
                INC DE
                JP NZ,SV1               ; Nee, => Volgende regel
                LD HL,(BUFPOINT)
                LD (HL),CTRLZ           ;EOF teken saven
                INC HL
                LD (BUFPOINT),HL
                CALL SAVEBUF            ;Leeg de buffer
                CALL CLOSEBF            ;Sluit bestand
                BIT BLOKFL,(IY+FLAGS1)  ;Bloksave?
                RET NZ                  ; Ja, => Klaar
                RES SAV,(IY+FLAGS1)     ;File niet meer saven na F4/S
                RET

                ;Leeg savebuffer

SAVEBUF:        LD DE,DISKBUF
                LD HL,(BUFPOINT)
                LD (BUFPOINT),DE        ;Pointer alvast leeg
                OR A
                SBC HL,DE               ;Bereken bufferlengte
                RET Z
                BIT DOS2,(IY-FLAGS5)
                JR Z,SVB1
                LD DE,DISKBUF
                LD C,WRITEFH            ;Schrijf naar DOS2 file handle
                LD B,(IY+DSKFLG)
                CALL DOS
                JR SVB2                 ;Test error
SVB1:           LD DE,FCB
                LD C,RBWRITE
                CALL DOS                ;Schrijf naar DOS1 FCB
                OR A
SVB2:           RET Z
                JP DISKVOL

endif                                   ;Einde van demo versie IF

                ;Volgende positie TABstop?

TABPOS:         PUSH HL
                LD E,A                  ;Bewaar teken
                LD B,0
                LD HL,TTAB+1
                ADD HL,BC               ;Bereken pos in TAB regel
                LD A,(HL)
                OR A                    ;Is er een TAB-stop?
                LD A,E                  ; Nee, vlag NZ
                POP HL
                RET

                ;Voeg een blok toe

LOADBLOK:       LD HL,TLOADNAM
                BIT DOS2,(IY-FLAGS5)    ;DOS2 pathname?
                JR Z,LB1
                INC HL                  ; Ja, sla de 3 tabs over
                INC HL
                INC HL
LB1:            LD C,1
                CALL INVOER             ;Haal naam bestand
                CALL NAAM
                RET C
LDBLK2:         LD A,OPEN               ;Entry voor blokload uit F3/Inhoud
                CALL MAAKFCB            ;Open de file
                JP C,NOTFOUND           ; Carry => Not found
                CALL RESETBLOK          ;Wis blokdefinitie
                LD A,(IY+TABSAV)
                PUSH AF
                RES UITVUL,(IY+TABSAV)
                CALL RETINS             ;Breek bestemming in 2en
                POP AF
                LD (IY+TABSAV),A
                CALL OPSLAAN            ; en bewaar 2e regel
                CALL RESTSCR            ;Herstel schermopbouw
                LD HL,(CSRNUM)
                PUSH HL
                LD (LOADREG),HL
                LD (BENDLN),HL
                LD (BSTARTLN),HL
                SET BLOKFL,(IY+FLAGS1)
                CALL LOAD3              ;Laad tekst in
                RES BLOKFL,(IY+FLAGS1)  ;Bloklaad flag wissen
                POP HL
                DEC HL
                LD (BSTARTLN),HL        ;Haal blokbegin
                INC HL
                CALL GOTOLINE
                JP BSPACE               ;Schuif blokbegin 1 regel omhoog

                ;Laad een tekst

LOAD:           CALL EVTOPSLAAN
                CALL VRAAGSAVE          ;Moet tekst bewaard worden?
                LD HL,0                 ;Tekst naar regel 0
                LD (LOADREG),HL
                LD HL,TLOADNAM
                BIT DOS2,(IY-FLAGS5)    ;DOS2 pathname?
                JR Z,LOAD1
                INC HL                  ; Ja, sla de 3 tabs over
                INC HL
                INC HL
LOAD1:          LD C,1
                CALL INVOER             ;Haal naam bestand
                LD E,1
                CALL GETFLEN            ;Haal naam lengte
                LD HL,LOADNAM           ;Haal oude (niet gevonden) naam
                CALL GETOLD             ;Voer naam in
                CALL NAAM2              ;Check naam/Extensie
                LD HL,LOADNAM
                LD (HL),0               ;Wis oude naam
                RET C                   ;Foute naam => terug
LOAD2:          BIT SVINS,(IY+SAVFL2)
                CALL NZ,LOADINS         ; Nee, laad *.TED instellingen bestand

                LD A,OPEN               ;Entry als naam in FCB1 staat
                CALL MAAKFCB            ;Open file
                JR NC,LO0B              ; Open geslaagd => LO0B
                CALL NOTFOUND           ; Carry => Not found
                LD DE,LOADNAM           ; Niet geslaagd, bewaar naam
                JP SFCB2
LO0B:           call clrNoPageTab       ;Wis stringgeheugen, behoud paginatabel
                CALL SAVFCB             ;Bewaar naam voor saven
                SET LDFL,(IY+FLAGS1)    ;Zet loading-vlag
                LD A,(IY+TABMAP)
                LD (IY+CURTAB),A        ;Huidige pointer segment = 1e
                CALL RTABHL             ;Lees beginadres van dat segment
                LD (PNTADR),HL          ;Adres van eerst volgende pointer
                LD A,(IY+BOTMAP)
                LD (IY+CURMAP),A        ;Huidig data=segment = 1e datasegment
                CALL READHL
                LD (DATADR),HL          ;Adres voor stringdata

LOAD3:          LD HL,LO1B              ;Entry voor blokladen
                PUSH HL
                LD HL,(TOCHK)
                JP (HL)                 ;Controleer checksum

MAKCTRL:        LD A,C                  ;Haal regellengte
                CP 252
                DEC HL
                JP NC,LO9               ;Te lang => Volgende regel
                INC HL
                LD A,DEL                ;A=Control voorloop kar (^)
                INC C                   ;C=Lower byte van STRBUF, addr 0C000H
                LD (BC),A               ;Vul ^-teken in de stringbuffer in
                LD A,'A'-1
                ADD A,(HL)              ;Code + 64 = contol-letter
                JP LO3B                 ;Vul control-letter in

; Entry voor (blok) laden
;
LO1B:           ld hl,tMoment
                call message            ;Momentje...
                call disVdpInt          ;VDP interrupts uitschakelen (sneller)

                ld hl,(loadReg)         ;Haal bestemmingsregel op
                push hl                 ;Bewaar op stack
                call update             ;Vul de buffer
                inc hl                  ;HL=Pointer naar begin van diskbuffer
                ld de,(endTPA)          ;DE=Einde van diskbuffer
                ld c,0                  ;C=Lengte van huidige regel

lo2:            ld b,high strBuf        ;B=Highbyte van stringbuffer op 0C000H
lo2b:           ld a,(hl)               ;Haal karakter uit diskbuffer
                cp 255                  ;Karakter 255?
                jr z,makCtrl            ; Ja, => Maak er een controlcode van
                cp del                  ;Delete-teken?
                jr z,lo8b               ; Ja, => Doe BS
                cp ' '
                jp nc,lo3b              ;JP = sneller als JR
                cp cr
                jr z,lo9
                cp lf
                jr z,lo9
                cp ctrlZ                ;CTRL Z?
                jr z,lo8c               ; Ja, => Klaar
                cp esc
                jr z,lo6                ;ESC mag wel (wordt ascii 0)
                CP BS
                JR Z,LO8B               ;BS => Wis teken
                CP TAB
                JR Z,LO5B               ;TAB => Evt. ascii 255 maken
                CP 1
                JR Z,LO7                ;Grafische opcode
                JP MAKCTRL              ;Vul ^-Code in voor code < 32
LO3:            LD B,HIGH STRBUF        ;B=Highbyte van stringbuffer op 0C000H
LO3B:           INC C                   ;C=Lower byte, skip lengtebyte, verhoog reglen
                LD (BC),A               ;Vul teken in de stringbuffer in
                LD A,C
                CP 253
                JR NC,LO9               ;Max 254 tekens
LO4:            LD A,L
                CP E
                LD A,H
                SBC A,D                 ;Load buffer leeg?
                LD A,(HL)               ;     Haal alvast volgende kar.
                CALL NC,UPDATE          ; Ja, => Update
                INC HL
                CP TAB                  ;Was teken een TAB?
                JP NZ,LO2B              ; Nee, => Ga verder
                PUSH HL                 ;Bewaar bronpointer
                LD B,0
                LD HL,TTAB              ;Bereken positie in regel
                ADD HL,BC
                LD A,(HL)               ;Cursor op tabstop?
                OR A
                POP HL
                JR NZ,LO2               ; Ja, => Ga verder
                DEC HL                  ; Nee, => blijf op TAB

LO5B:           BIT LDTAB,(IY+TABSAV)   ;Tabs direkt laden?
                LD A,' '
                JR Z,LO3                ; Nee, => maak rijtje spaties
                LD A,255                ;TAB=Code 255
                LD (HL),A               ;Geen spaties van maken (zie LO5)
                JR LO3

LO6:            XOR A                   ;ESC=Code 0
                JR LO3

                ;Haal grafische code

LO7:            LD A,L
                CP E
                LD A,H
                SBC A,D                 ;Load buffer leeg?
                CALL NC,UPDATE
                INC HL
                LD A,(HL)
                SUB 'A'-1               ;Bereken code
                JR LO3B

LO8B:           LD A,C                  ;Back Space=>Teken terug
                OR A                    ;Regellengte=0?
                JP Z,LO4                ; Ja, => Klaar
                DEC C
                JP LO4

LO8C:           INC C                   ;Ctrl/Z, kijk of de regellengte 0 is
                DEC C
                JR Z,LO13               ; Ja, => Sluit het bestand

LO9:            LD A,C
                LD (STRBUF),A           ;Vul regellengte in
                POP DE                  ;Haal regnr. in DE
                INC DE                  ;Verhoog met 1
                PUSH DE
                PUSH HL                 ;Bewaar bronpointer
                LD HL,STRBUF            ;Geef regeladres aan
                BIT BLOKFL,(IY+FLAGS1)  ;Blok laden?
                JP Z,LO9B               ; Nee, => Plak zin achter in het
                DEC DE                  ;         stringsegment
                CALL VOEGIN             ; Ja, voeg stringpnt. in
                LD A,(HL)
                OR A                    ;Str. len = 0?
                JR Z,LO9C               ; Ja, => Klaar
                LD DE,LO9C              ;Zet RET-adres op de stack
                PUSH DE
                BIT LDTAB,(IY+TABSAV)   ;Tab's direct laden van disk?
                JP NZ,ZR0B              ; Ja, => Alle Tabs staan er al in
                JP ZR0A                 ; Nee, => Maak TABs van spaties
LO9B:           CALL PUTLAST            ;Bewaar regel snel
LO9C:           LD DE,(ENDTPA)          ;DE=Einde van loadbuffer
                POP HL                  ;Haal bronpointer
                LD C,0                  ;Nieuwe regel, => lengte=0
                LD A,(HL)
                CP CTRLZ                ;EOF?
                JR Z,LO13               ; Ja, => Sluit bestand
                LD B,LF
                CP CR                   ;1e teken CR?
                JR Z,LO10               ; => LF ook overslaan
                LD B,CR
                CP LF
                LD B,HIGH STRBUF        ;B=Highbyte van stringbuffer op 0C000H
                JP NZ,LO4               ; Geen LF,CR => Volgende string
                LD B,CR
LO10:           LD A,L
                CP E
                LD A,H
                SBC A,D                 ;Load buffer leeg?
                CALL NC,UPDATE
                INC HL
                LD A,(HL)
                CP B                    ;Volgt na CR een LF of andersom?
                JP NZ,LO2               ; Nee, => Hier start volgende string
                LD B,HIGH STRBUF        ;      B=Highbyte van stringbuffer
                JP LO4                  ; Ja, => Skip het teken

LO13:           POP HL                  ;Haal laatste regelnummer
                BIT BLOKFL,(IY+FLAGS1)  ;Bezig met blokladen?
                JR Z,LO15
                LD (BENDLN),HL          ; Ja, vul blokeinde in
                JR LO16
lo15:           ld hl,(pntAdr)          ; Nee, haal eind-adres van pnt. seg
                call wTabHL             ;bewaar einde huidige pointersegment
                ld hl,(datAdr)          ;Eindadres van data segment
                call writeHL
                ld hl,0                 ;Ga naar de 1e regel
                call gotoLine
                res ldFl,(iy+flags1)    ;Wis de loading-vlag
lo16:           call closeBf            ;Sluit het bestand
                call chkPageTab         ;Verwijder evt. illegale paginastops
                or a                    ;Geen carry => Laden o.k.
                ret

                ;Vul de loadingbuffer bij, nieuwe pointer in HL

UPDATE:         PUSH DE
                PUSH BC
                PUSH AF                 ;AF ook behouden
                LD C,0                  ;Laatste regel mag worden weggemikt
                LD HL,DISKBUF           ;Hier begint de diskbuffer
                JR UD2B                 ;Bijvullen aub

UPDAT2:         PUSH AF                 ;AF ook behouden
                LD HL,(ENDTPA)
                INC HL
                LD A,C                  ;Restje van laatste regel ophalen?
                OR A
                JR Z,UD2                ; Nee, => UD2
                PUSH BC                 ;BC=Rest. len
                SBC HL,BC
                LD DE,DISKBUF
UD1:            LDIR                    ;Verplaats rest naar begin van buffer
                POP BC
UD2:            LD HL,DISKBUF
                ADD HL,BC               ;Bereken beginadres

UD2B:           PUSH HL                 ;Bewaar beginadres
                EX DE,HL
                LD C,SETDMA
                BIT DOS2,(IY-FLAGS5)    ;DOS2?
                CALL Z,DOS              ; Nee, => Zet beginadres
                LD HL,(ENDTPA)          ;Bereken te lezen lengte
                INC HL
                POP DE                  ;Haal beginadres
                PUSH DE
                OR A
                SBC HL,DE
                BIT DOS2,(IY-FLAGS5)    ;DOS2?
                JR Z,UD3                ; Nee, => lees uit FCB
                LD C,READFH             ; Ja, lees uit file handle
                LD B,(IY+DSKFLG)        ;Haal file handle
                CALL DOS                ;Lees HL bytes in DE
                JR UD4
UD3:            LD DE,FCB               ;Lees uit FCB
                LD C,RBREAD
                CALL DOS                ;Lees data van schijf
                OR A
                JR Z,UD5                ;Geen teksteinde => Klaar
UD4:            POP DE
                PUSH DE
                ADD HL,DE               ;Bereken adres laatste byte + 1
                LD (HL),CTRLZ           ;Na teksteinde EOF invullen
UD5:            POP HL
                DEC HL
                POP AF                  ;Herstel registers
                POP BC
                POP DE
                RET

                ;Open / Cre‰er tekst

MAAKFCB:        BIT DOS2,(IY-FLAGS5)    ;DOS2 aanwezig?
                JR Z,MFDOS1             ; Nee, => maak FCB
                PUSH AF
                CP CREATE               ;Creeer file handle?
                JR Z,MFH2
                LD A,1                  ; Nee, => Open read-only file handle
                LD DE,BUF+1             ;DE=Pathname adres
                LD C,OPENFH             ;Open file handle
                CALL DOS
MFH1:           JP NZ,MKF1              ;=> Error
                POP AF
                LD (IY+DSKFLG),B        ;Bewaar filehandle
                OR A
                RET
MFH2:           BIT BKUP,(IY+SAVFL)     ;Backup maken?
                JR Z,MFH5
                LD HL,BUF
                LD DE,path1Buf          ; Ja, bewaar path/filenaam in BUF+125
                LD BC,65
                LDIR
                LD BC,PARSE
                LD DE,BUF+1
                CALL DOS                ;Parse pathname
                BIT 3,B                 ;Filenaam aanwezig?
                JP Z,MKF1               ; Nee, => Bestandsnaam fout
                PUSH HL                 ;Bewaar beginadres van filename
                BIT 4,B                 ;Extensie aanwezig?
                JR Z,MFH4
MFH3:           LD A,(HL)               ; Ja, zoek de '.'
                INC HL
                CP '.'
                JR NZ,MFH3
                DEC HL
                EX DE,HL
MFH4:           EX DE,HL
                LD (HL),'.'             ;Maak extensie .BAK
                INC HL
                LD (HL),'B'
                INC HL
                LD (HL),'A'
                INC HL
                LD (HL),'K'
                INC HL
                LD (HL),0
                LD DE,BUF+1
                LD C,DEL2               ;Wis oude '.BAK' file
                CALL DOS
                POP HL
                LD DE,path1Buf+1        ;Rename originele file in '.BAK'
                LD C,REN2
                CALL DOS
                LD HL,path1Buf
                LD DE,BUF
                LD BC,65
                LDIR                    ;Herstel filenaam
MFH5:           LD DE,BUF+1
                LD BC,CREATEFH          ;Create normal file handle
                LD A,10B                ;Write only
                CALL DOS
                JR MFH1                 ;Test error

MFDOS1:         LD HL,FCB1              ;Haal naam op
                LD BC,12
MFDOS1B:        LD DE,FCB
                PUSH DE
                LDIR
                PUSH AF                 ;Bewaar DOS-open/create
                CP CREATE               ;Bestand maken?
                JR NZ,MKF0              ; Nee, => Geen controle
                BIT BKUP,(IY+SAVFL)     ; Ja, backup maken?
                JR Z,MKF0
                LD HL,FCB
                LD DE,FCB+16            ; Ja, maak 2e FCB
                PUSH HL
                PUSH DE
                LD BC,9
                LDIR
                EX DE,HL
                LD (HL),'B'             ;Maak extensie .BAK
                INC HL
                LD (HL),'A'
                INC HL
                LD (HL),'K'
                POP DE
                LD C,DELFILE
                CALL DOS                ;Wis evt. oude .BAK
                POP DE
                LD C,RENAME
                CALL DOS                ;Maak oude origineel .BAK
MKF0:           XOR A
                LD (FCB+12),A           ;Wis extentbyte van FCB
                POP AF
                POP DE
                LD C,A
                PUSH AF
                CALL DOS                ;Open/cre‰er file
                OR A
                JR NZ,MKF1              ;ERROR
                POP AF
                LD HL,1
                LD (GROOTTE),HL
                LD (IY+DSKFLG),L        ;1 File open
                DEC HL
                LD (BLOK),HL
                LD (BLOK+2),HL
                OR A
                RET
MKF1:           POP AF
                CP CREATE               ;Saven?
                JR Z,TOOMANY            ; Ja, toomany files
                SCF
                RET

TOOMANY:        LD HL,TTOMANY
                CALL MESKEY
                SCF
                RET

                ;Zet string achter laatste regel
                ;HL=String adres
                ;DE=Regelnummer
                ;C=Lengte

PUTLAST:        PUSH HL
                BIT LDTAB,(IY+TABSAV)   ;Tab's direct laden van disk?
                JP NZ,PL0               ; Ja, => Alle Tabs staan er al in
                BIT STTAB,(IY+TABSAV)   ; Nee, moeten ze wel berekend worden?
                JR Z,PL0                ;  Nee, => Geen STore TABs
                INC C                   ;Lege string bewaren?
                DEC C
                JR Z,PL0                ; Ja, => Geen tabs omvormen
                PUSH DE
                CALL MAKETAB            ;  Ja, maak string met TAB's
                POP DE                  ;Herstel regelnummer
                EX (SP),HL              ;Bewaar nieuwe stringadres, oude weg
                LD C,A                  ;Haal (verkorte) stringlengte
PL0:            LD A,(IY+CURTAB)        ;Haal huidig pointersegment
                CALL MMOUT              ;Schakel dat in
                LD HL,(PNTADR)          ;Haal adres voor volgende pointer
                PUSH HL                 ;Bewaar pointeradres
                BIT 6,H                 ;Past pointer in deze pagina?
                INC HL                  ; Bereken alvast volgende pointer adres
                INC HL
                INC HL
                INC HL
                JR Z,PL1                ; Ja, => zoek naar data-ruimte
                POP HL                  ; Nee, haal pointeradres  van de stack
                CALL WTABHL             ;Bewaar dat in de eind-adressen tabel
                DEC A                   ;Installeer een nieuw pointer segment
                CP (IY+DATAMAP)         ;Volgende segment vrij?
                JR Z,LOADMEMVOL         ; Nee, => Error tonen
                CP 7
                JR Z,LOADMEMVOL         ; Nee, => Geen VRAM voor pointertabel
                LD (IY+CURTAB),A        ; Ja, alloceer een nieuw pointersegment
                LD (IY+TABMAP),A        ;Bewaar nummer laaste pointer segment
                CALL MMOUT              ;Schakel het segment in
                EX DE,HL                ;Regelnummer even in HL bewaren
                CALL GETBOT2            ;Haal beginadres van het segment in DE
                EX DE,HL                ;,, in HL
                PUSH HL                 ;Beginadres wordt adres voor nieuwe pnt
                INC HL                  ;Eindadres van het segment ligt 4 bytes
                INC HL                  ; voorbij de pointer
                INC HL
                INC HL
PL1:            LD (PNTADR),HL          ;Bewaar nieuwe pointersegment eindadres
                LD (LASTLINE),DE        ;Bewaar regelnummer laatsteregel + 1

                LD HL,(DATADR)          ;Haal volgende data-adres
                LD D,H                  ; in DE en HL
                LD E,L
                LD B,0                  ;BC=Stringlengte
                ADD HL,BC
                BIT 6,H                 ;Past de string nog in het segment? (H < 0C0H)
                JR Z,PL3                ; Ja, => String naar [DE]
                LD HL,(DATADR)          ; Nee, bewaar eindadres van dit
                CALL WRITEHL            ;  datasegment
                LD A,(IY+CURMAP)        ;Haal nummer huidige data-segment
                INC A                   ;We pikken een nieuwe in
                CP (IY+TABMAP)          ;Pointersegement bereikt?
                JR NZ,PL2               ; Nee, => Segment is vrij
                POP HL                  ;Haal pointeradres
                INC HL
                LD (HL),0               ;Zet de stringlengte op 0
                JR LOADMEMVOL           ;Geef melding "Geheugen vol"
PL2:            LD (IY+DATAMAP),A       ;Bewaar laaste data segment
                LD (IY+CURMAP),A        ;Bewaar huidige data segment
                CALL GETBOT2            ;Haal beginadres van dit segment in DE
                LD H,D                  ;Beginadres van het segment naar HL
                LD L,E
                ADD HL,BC               ;Bereken eindadres van stringdata seg.
PL3:            LD (DATADR),HL          ;Dat is begin-adres voor volgende keer
                LD A,(IY+CURMAP)
                POP HL                  ;Haal pointeradres van de stack
                LD (HL),A               ;Zet datasegment nummer in de pointer
                INC HL
                LD (HL),C               ;Stringlengte
                INC HL
                LD (HL),E               ;En het stringadres
                INC HL
                LD (HL),D
                POP HL                  ;Haal string bron-adres
                INC C
                DEC C                   ;Stringlengte 0?
                RET Z                   ; Ja, => Klaar
                INC HL                  ;Lengte byte overslaan
                CP 8                    ;Is het datasegment in VRAM?
                JP C,LDRVM2             ; Ja, => string naar VRAM
                CALL MMOUT              ; Nee, schakel het segement in page 2
                LDIR                    ;String naar data segment
                RET
LOADMEMVOL:     LD HL,TMEMVOL
                CALL MESKEY             ;Melding "Geheugen vol"
                JP ERROR                ;Sluit Filehandles etc.


; disVdpInt
;
; Schakel VDP interrupts uit
;
; Wijzigt: A, C
;
disVdpInt:      ret
                ld c,(iy-vdpCw)         ;C=VDP command poort
                ld a,(rg1sav)           ;Waarde van register 1
                and 11011111b           ;Bit 5 op 0 zetten
                ld (rg1sav),a
                out (c),a               ;Databyte naar VDP
                ld a,1 + 80h            ;Data moet naar register 1
                out (c),a
                ret


; enaVdpInt
;
; Schakel VDP timer interrupt in.
;
; Bug: Verstoort soms de schermopbouw indien aangeroepen via CHSNS
;
; Wijzigt: A, C
;
enaVdpInt:      ld a,(rg1sav)           ;Waarde van register 1
                bit 5,a                 ;Interrupts reeds aan?
                ret nz                  ; Ja, => Klaar
                ld c,(iy-vdpCw)         ;C=VDP command poort
                or 00100000b            ;Bit 5 op 1 zetten
                ld (rg1sav),a
                out (c),a               ;Databyte naar VDP
                ld a,1 + 80h            ;Data moet naar register 1
                out (c),a
                ret


defFcb:         db 0

if              DEMO or AUTODEMO
tTed:           db 'TEDDEMO COM',0      ;FCB naam + extent byte
else
tTed:           db 'TED     COM',0
endif

defEnd          equ $

if1
                .printx * Pass 1 done *
else
                .printx * Pass 2 done *
endif

                end                     ;SUBTED.MAC
